### ISSUE TITLE
Fly Wing can not entry into mission mode

### ISSUE THREAD

**Issue by RollinsYang** [PX4/Firmware#10057]
Fly Wing can not entry into mission mode.

here is the log:  https://logs.px4.io/plot_app?log=3ede1a11-2da2-4d10-a582-3ef78658769e

@priseborough could you take a look at these logs?

**Comment by dagar** [comment]
@RollinsYang the reason you couldn't enter mission is because you didn't have a valid mission on the vehicle. When you sync via QGC you should have seen an error message, although it could have been hidden by a different error.

![image](https://user-images.githubusercontent.com/84712/43328192-58b9dc1e-918b-11e8-81dc-35549d706923.png)

In your specific case I'm guessing you had a landing mission item, but without a waypoint before it to approach. I would suggest upgrading to the latest QGC + PX4 stable versions and add a landing by selecting "Fixed Wing Landing" under Pattern.

![image](https://user-images.githubusercontent.com/84712/43328400-e517a0a6-918b-11e8-9f4f-1df17446e1aa.png)



This type of error feedback is something we need to improve.
