### ISSUE TITLE
Broken links on I2C page

### ISSUE THREAD

**Issue by jonathan84clark** [PX4/Firmware#10209]
The page https://dev.px4.io/en/sensor_bus/i2c.html has broken links to the examples in the I2C Driver Examples page
https://github.com/PX4/Firmware/tree/master/src/drivers/sf1xx
https://github.com/PX4/Firmware/tree/master/src/drivers/ms5611

**Comment by hamishwillee** [comment]
Thanks very much @jonathan84clark ! Fixed by https://github.com/PX4/Devguide/commit/cc08775f41814cd84847a518dd67459a89f021a1

FYI, you can fix these yourself easily enough by clicking the edit icon on the top of the page - [more information here](https://dev.px4.io/en/contribute/docs.html#quick-changes).
![image](https://user-images.githubusercontent.com/5368500/44013220-88c69df0-9f07-11e8-9668-4949ebd346e5.png)
