### ISSUE TITLE
Tailsitter VTOL orientation in FW mode

### ISSUE THREAD

**Issue by abdulmajid92** [PX4/Firmware#10405]
I have developed quad tailsitter vtol. The aircraft orientations have an issue when the aircraft transition from MC mode to FW mode, the aircraft orientation was showed that the aircraft has pitched 90 degree down (still MC orientation, it should be change to FW orientation). Anybody can help this issue?

Thanks

**Comment by dagar** [comment]
@RomanBapst @bresch @jlecoeur I know this has been discussed before, but stalled for various reasons. Thoughts?

**Comment by jlecoeur** [comment]
1. I can't find it now but I remember reading in a QGC issue that this solution would put too much airframe logic on QGC side (and be a precedent justifying more special cases), something they did not want.

2. This requires extending a mavlink message. While we are at it, why not add a quaternion in VFR_HUD? This message is the perfect candidate to provide a human-oriented feedback on attitude. This way, the Firmware is responsible for computing the HUD attitude, blending is possible, ATTITUDE_QUATERNION is untouched for offboard users, and we just need to change  QGC's hud to use the quaternion in VFR_HUD instead of ATTITUDE_QUATERNION.

**Comment by abdulmajid92** [comment]
@jlecoeur @RomanBapst 
I have explored a FixedwingAttitudeControl code, and found this one. Can we implement this one to mavlink message (attitude)?
![capture](https://user-images.githubusercontent.com/14164260/45014940-567e8200-b04a-11e8-8fdf-c16135079e0a.JPG)

**Comment by jlecoeur** [comment]
@abdulmajid92 Yes, that is the attitude we would like to display on QGC, however, we cannot send it directly in the attitude & attitude_quaternion mavlink messages because these messages are also used by companion computers, who need consistent attitude before, during and after VTOL transitions.

 @dagar @RomanBapst What is your view on the VFR_HUD option?

**Comment by RomanBapst** [comment]
@abdulmajid92 Is that something you could help pursuing?

**Comment by bresch** [comment]
@jlecoeur This is still not solved right?

**Comment by jlecoeur** [comment]
@bresch no, still unsolved.

@dagar @RomanBapst unless you have another option, or strong feeling against it, let's create a MAVLink RFC to extend VFR_HUD. An RFC may lead to interesting discussions because Ardupilot does it differently: it currently sends rotated VTOL attitude directly in the attitude message.

**Comment by julianoes** [comment]
@RomanBapst what's the state here?

**Comment by jlecoeur** [comment]
solved in #13249
