### ISSUE TITLE
Restore LNDMC_THR_RANGE for faster disarm on land

### ISSUE THREAD

**Issue by dakejahl** [PX4/Firmware#10712]
As of https://github.com/PX4/Firmware/commits/master/src/modules/land_detector the land detector cannot be configured to transition from `ground_contact` to `maybe_landed` via the now deprecated parameter LNDMC_THR_RANGE. 

It now takes a considerable amount of time to disarm due to throttle down time.
https://review.px4.io/plot_app?log=43987a80-5752-4f55-89a7-eec60e9298c3
![selection_011](https://user-images.githubusercontent.com/37091262/47110927-65428200-d20f-11e8-8e41-0ab7008884d7.png)
![selection_013](https://user-images.githubusercontent.com/37091262/47110989-8a36f500-d20f-11e8-86b4-ef158f78e931.png)

If there is a better way to do this lets discuss it, otherwise I think the parameter should be restored.

**Note:** current implementation sets a hard coded limit
```
// 10% of throttle range between min and hover once we entered ground contact
float sys_min_throttle = _params.minThrottle + (_params.hoverThrottle - _params.minThrottle) * 0.1f;
```

**Comment by bkueng** [comment]
You can configure `COM_DISARM_LAND` to less than a second.
@MaEtUgR anything else?

**Comment by dakejahl** [comment]
I do have a question, why does it take so long for the vehicle to throttle down after ground contact?
![selection_011](https://user-images.githubusercontent.com/37091262/47166314-21a45280-d2b9-11e8-9904-21629217dc47.png)

**Comment by MaEtUgR** [comment]
@dakejahl You found the weak point of the land detection. I also noticed that with the default PX4 tuning parameters it usually takes very long to detect landing. With our specific build we tuned the altitude control and `LNDMC_THR_RANGE` and `COM_DISARM_LAND` such that it detects landing very quickly (I would say faster than the DJI Phantom 4 did in my tests). The problem with the defaults is that you usually want to stay on the safe side. I know that our tuning works well with our build but have no idea if that's safe tuning in general.

> why does it take so long for the vehicle to throttle down after ground contact

I think that's because when you push down it controls the downwards velocity and not the position, RTL e.g. controls the position and usually lands much quicker. Then it depends on the vertical velocity control tuning which by default is conservative. And the slow aggregation of less and less thrust is then the integrator control of the vertical velocity. So if that theory is true you could make landing detection almost impossible by setting `MPC_Z_VEL_I` to zero.

If that helps you any further here are the build specific parameters we successfully use for very fast land detection:
```
param set MPC_Z_VEL_P 0.25 # default 0.2
param set MPC_Z_P 0.85 # default 1.0
param set MPC_Z_VEL_D 0.0 # default 0.0
param set MPC_Z_VEL_I 0.085 # default 0.02

param set COM_DISARM_LAND 0.1 # default -1 (desabled)
# LNDMC_ are all on default
```
But be careful trying the out, it could result in altitude oscillations and instability on your vehicle. Always have manual mode at hand to save your vehicle.

**Comment by MaEtUgR** [comment]
@bkueng If it doesn't improve landing behaviour yes. We can also revert the fix that restored all landing states as they were designed but apparently now prolongs all landing detections. At least as a hotfix until we have something better to not make people hate landing detection. We did that for H520 now.
