### ISSUE TITLE
CUAV V5 debug: Board 105 is not supported

### ISSUE THREAD

**Issue by cuhome** [PX4/Firmware#10976]
Firmware: master branch firmware (fmu v5) downloaded online on qgc
problem:Board 105 is not supported（The fault has been fixed in the 1.80/1.81stable firmware, but the new master firmware reproduces this problem.）
![cuavv5 2](https://user-images.githubusercontent.com/31507501/49426143-97696c80-f7da-11e8-9945-51aae1aefebc.png)

**Comment by davids5** [comment]
@jinger26 

This is not a bug or fault or regression - Version 1.8.0, 1.81 did not check the hardware revision nor provide a manifest. 

Product was shipped without getting a REV and VER assigned by PX4. 

As shipped it is not supported and I believe that is because SBUS RC does not work because it is wired differently than the FMUv5 pin out. 

Please discuss with @LorenzMeier and let me know how you would like to resolve this.

**Comment by davids5** [comment]
@cuhome - please test with https://github.com/PX4/Firmware/pull/10982
