### ISSUE TITLE
Incremental build issues for IO

### ISSUE THREAD

**Issue by bkueng** [PX4/Firmware#11036]
- incremental build for the IO is broken, i.e. a change to the IO firmware code is not included in a subsequent build.
- `make/ninja clean` in `build/px4_fmu-v5_default` does not clean the IO build. However a subsequent build rebuilds the IO.

**Comment by dagar** [comment]
The way this works is the px4io driver initiates the px4_io-v2 build. Previously this was done by calling make directly from a cmake custom command. Recently I changed it to use cmake ExternalProject (https://cmake.org/cmake/help/latest/module/ExternalProject.html) to work around a number of cmake IDE related issues.

The dependencies were never quite right in the previous setup. I'll look for a way we can use the real underlying dependencies with ExternalProject so that final px4 binary isn't rebuilt constantly.

**Comment by bresch** [comment]
The issue is still there: every time I want to test a modification I did in px4iofirmware, I have to do a `make clean` before I rebuild to include the changes.
