### ISSUE TITLE
remote PX4 firmware upgrade through mavlink

### ISSUE THREAD

**Issue by xiaofyao** [PX4/Firmware#11106]
Hi,

We need remote PX4 firmware upgrade function instead of local QGC burn.
So I wonder if we can upgrade the PX4 firmware through mavlink. Does PX4 support this operation now?

Br,
xiaofyao

**Comment by metinburak** [comment]
In order to upload firmware, u should set the fun to bootlader mode, u can do it via mavlink, but after setting it to boot loader mode, it doesn’t mean u can upload firmware through mavlink. Or the long way is to handle the firmware file via mavlin and let Fmu mavlink handler write it down to the flash’s specific region, then letting the boot loader check a magic word there and jump to the firmware at the start up.
