### ISSUE TITLE
Battery configuration: Inaccurate Voltage-based Estimation Fused with Current Integration

### ISSUE THREAD

**Issue by alessio-zatti** [PX4/Firmware#11121]
Hi Team,
I'm working with PIXHAWK4 equipped with the Power Module PM07.

Battery: 3S 5000mAh 50C (I always used full charged battery) - 3mOhm the internal R
Frame: Quadcopter FJ450
Motors: 2312E DJI
ESC: BLHeli 30A

Trying to configure and tune the battery module, I found issues with the Voltage-based Estimation method.
I configured all the parameters according to the guide https://docs.px4.io/en/config/battery.html but the battery remains percentage decrease quickly (from 100% to 30% in no more than two minutes). Checking the battery status at the end of my test this discharging ramp is not correct.

I configured the current compensation method and the percentage is more reliable.

You can check the log:

USING THE VOLTAGE-BASED METHOD:
[https://logs.px4.io/plot_app?log=1e248411-e512-40ec-9bda-e6f5867728d7](http://url)

USING THE CURRENT COMPENSATION:
[https://logs.px4.io/plot_app?log=6b86e36c-4521-43e9-83f6-32088ba9a01d](http://url)

What I'm doing wrong?

I checked the code and I found something strange. It seems the first value of _remaining is discarded. Im referring to this method:

https://github.com/PX4/Firmware/blob/542cd7f2167af65e1680047cdca25ceb9a73bd6c/src/lib/battery/battery.cpp#L167-L204

I'm referring to this part:

https://github.com/PX4/Firmware/blob/542cd7f2167af65e1680047cdca25ceb9a73bd6c/src/lib/battery/battery.cpp#L191-L198

Thanks
Alessio

**Comment by hamishwillee** [comment]
@MaEtUgR Might be something you can help with?

**Comment by alessio-zatti** [comment]
Hi Hamish,
I had some trouble configuring the battery. To compare the two methods ("Current-based load compensation" and "voltage-based estimate merged with the current integration") I fixed the drone on the ground and I used a tester to measure the current. With the throttle stick low the value shown by QGroundControl and the value measured by the tester are very different, but when I moved the stick to the center (in hovering if the drone was free to fly) the two values are equal (~8A) but in one case, that one with the parameter BAT_CAPACITY equal to 4500 ("voltage-based estimate merged with the current integration") the capacity percentage decreased very quickly. 
I do not undestand this behaviour.

Thanks

**Comment by hamishwillee** [comment]
@alessio-zatti Thanks for the information. I am not particularly familiar with this either, but @MaEtUgR is, and should be able to comment when he returns from his summer break.

**Comment by MaEtUgR** [comment]
@alessio-zatti Sorry to hear about your problems. I replaced your code citations with GitHub references to the current implementations. Let me have a look at the log. I didn't spot the cause yet.

> I checked the code and I found something strange. It seems the first value of _remaining is discarded.

The battery estimation values are initialized to default values on boot because the potentially unavailable hardware reporting the measurements is not initialized at the time. When the first useful value is received the initialization is redone based on the first voltage measured because otherwise the filter would very slowly converge towards the correct battery state.

The else block you referenced is a complementary filter that fuses voltage and current based estimate and adjusts the weight towards the end of the battery's life because when the voltage drops too low that's a known hard limit and trust on current based measurement is reduced.

Generally if the voltage based method doesn't work properly it needs to be correctly configured first. The advantage of current based estimation is foremost a more stable estimation under dynamic load and a more accurate estimation when starting with a full battery.
