### ISSUE TITLE
Gazebo stuck when simulating multiple UAVs

### ISSUE THREAD

**Issue by SamNew1** [PX4/Firmware#11156]
I followed the link: https://dev.px4.io/en/simulation/multi-vehicle-simulation.html
But when I enter: "roslaunch px4 multi_uav_mavros_sitl.launch", Gazebo got stuck showing preparing your world. I have no problem in simulating one vehicle, but stuck in simulating multiple vehicles. I am using the latest PX4/Firmware. Is there anyone who can help me? Thank you in advance!

**Comment by aomezzine** [comment]
Hi,
I have the same problem when launching  w multi_uav_mavros_sitl.
Note that it works fine with an older version of the Firmware (downloaded on December).
Thank you for your help.

**Comment by billiepratama** [comment]
@SamNew1 Hello, i got the exactly same problem with you. Gazebo got stuck and just preparing the world. Then, i tried to clean by "make clean" in the directory Firmware directory. I tried to roslaunch px4 multi_uav_mavros_sitl.launch and it worked. But, now the problem is mavros topics don't publish any values. I hope that anyone can help this issue.

**Comment by julianoes** [comment]
Did you have any success fixing this? As far as I know this should be working.

**Comment by billiepratama** [comment]
What is your problem? Maybe i can help you.
In my case, i tried to upgrade my ubuntu version to 18.04 and install ROS
Melodic. After that, everything works fine.

Le mer. 10 juil. 2019 à 19:08, Julian Oes <notifications@github.com> a
écrit :
