### ISSUE TITLE
Accels inconsistance and No X,Y estimation

### ISSUE THREAD

**Issue by E666GT** [PX4/Firmware#11526]
Q1:
Always show accels inconsistance check cal. What's the supposed problem？ Even though I tried calibrated, sometimes it work some times not.

Does it because my pixhawk is too old？ (hardware: Pixhawk)

Q2

And there is always no x,y position estimation in the log. Is this problem caused by bad health of GPS？ 

When I use Qground App, I see 0 satellite under the GPS icon, is this a problem？

I use branch v1.9.0a

**Comment by bozkurthan** [comment]
A1:
In my opinion the problem is related to this issue #10833 . The issue was solved 1 month ago. You can update your Firmware to latest branch. Addition, Accelometers need to carefully calibrate. So, when you're calibrating the your platform, don't move any rotation even slowly until hear the buzzer sound. ( I was involuntarily shaking my hand little bit while calibrating. ) Also, the accelometers don't need calibration every time like magnometers for changing environment. 

A2: 
Maybe you should change LOG parameters from parameter list in QGroundControl.
If you work inside the building or very cloudy day, it's normal to see 0 satellite. Try to test outside and if you still has no satellite, yes, there is a problem.
