### ISSUE TITLE
yaw_sp_move_rate reset on ground

### ISSUE THREAD

**Issue by yukun2016** [PX4/Firmware#11809]
Software version 1.8.0
Maybe the  flag **_att_sp.yaw_sp_move_rate** should be reset when **_reset_yaw_sp** is true.

**Comment by julianoes** [comment]
@MaEtUgR is this still relevant with 1.9.0 ?

**Comment by MaEtUgR** [comment]
This is not relevant for 1.9 anymore since we got rid of this error prone global position control module logic here: https://github.com/PX4/Firmware/commit/e51e1bbe7414abf0cb80f1618ca9c46ba36e84ad#diff-fc77c3ef569029d45764664c75d4b0c1L135

@yukun2016 Thanks for reporting, could you test 1.9 beta? Do you see any specific symptoms? I'm closing this but feel free to reopen if you have a more detailed description.
