### ISSUE TITLE
Logger out of FD (VTOL)

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#11810]
A VTOL flight on current master produces the following warnings:
![image](https://user-images.githubusercontent.com/7610489/55710247-7e700280-59ea-11e9-888b-1b7ade189f92.png)

Log:
https://logs.px4.io/plot_app?log=9d52d3cc-db49-4178-9ce0-2faeb239ff19

**Comment by dagar** [comment]
As an immediate fix for v1.9.0 we need to reduce the default topics here. https://github.com/PX4/Firmware/blob/d9f8e37288d8e34baac79b32d71862045946534b/src/modules/logger/logger.cpp#L614-L660

Post v1.9.0 let's push on https://github.com/PX4/Firmware/pull/11176 so that the file descriptor limit stops getting in the way.
