### ISSUE TITLE
Adding an Airspeed Sensor to a Generic Quadrotor x

### ISSUE THREAD

**Issue by NoahStorm** [PX4/Firmware#11869]
Hello!

We are an Aerospace Engineering design team at the University of Minnesota trying to fly a quadcopter with an mRo Next-Gen MS5525 Airspeed sensor. We know that Qgroundcontrol does not allow an airspeed sensor to be added when using the Generic Quadrotor x airframe configuration by default. 

We are new to this, so I am not sure how to update the config file (if that is even the right approach) to allow for an airspeed sensor to be used. Has anyone had any luck putting an airspeed sensor on a quad? 

Thanks!

**Comment by dagar** [comment]
Hi @NoahStorm, 

The only reason the airspeed sensors aren't started automatically on multicopters is because of the check here. https://github.com/PX4/Firmware/blob/3d36dbfba385a81e5bc7d814febd2ae991e2017b/ROMFS/px4fmu_common/init.d/rc.sensors#L34

We could probably remove that entirely if desired. QGroundControl might not show the option to calibrate, but you can still do it on the command line (`commander calibrate airsped`).

**Comment by NoahStorm** [comment]
Thanks for your reply @dagar 

We tried the command you gave and we got the following error message:

![Screen Shot 2019-04-17 at 10 20 51 AM](https://user-images.githubusercontent.com/24260163/56301881-59704380-60fe-11e9-81c2-31263389fb53.jpeg)

Our air speed sensor calibrates just fine when we set the Pixhawk Mini to the fixed wing airframe configuration. How could we go about changing that if-statement in the sensors code?

**Comment by julianoes** [comment]
@NoahStorm were you able to figure this out?

**Comment by julianoes** [comment]
No answer, closing.
