### ISSUE TITLE
Update `gnd_pos_control` and `ground_att_control` modules

### ISSUE THREAD

**Issue by ItsTimmy** [PX4/Firmware#11956]
**Describe problem solved by the proposed feature**
The current rover position and attitude control modules are based on fixed-wing control. They work for simple waypoint navigation, but should be updated to account for different types of steering (Ackerman vs. Differential steering) and limitations of rovers. Additionally, rovers behave strangely around edge cases, such as when the `navigator` module would instruct a fixed-wing craft to loiter, and when instructing the rover to "take off" or "land".

**Describe your preferred solution**
Research existing control algorithms for Ackerman and Differential steering vehicles, and implement them in the `gnd_pos_control` and `gnd_att_control` modules.

**Describe possible alternatives**
The existing modules implement Ackerman control, so a new separate module could be created for differential steering.

**Comment by julianoes** [comment]
From call:
@ItsTimmy: differential controller spins in circle when waypoint reached.
@dagar: differential steering rover controller could work like multicopter controller. We could have two controllers, one for Ackermann, one for differential steering.

**Comment by SalimTerryLi** [comment]
Can we add another parameter to determine whether the rover should do in-situ turning or directly move forward while do steering?
I' m looking forward to a solution which can dynamically switch between Ackermann & differential steering. Because I want my rover can have a fluent behavior in wide area but also can easily adapt into limited space. (with the help of RTK)
We can build a simple framework in gnd_position_control at first and then finish the codes for differential steering?
Or, any better ways?

**Comment by julianoes** [comment]
@ItsTimmy can you make a pull request for this change?

**Comment by ItsTimmy** [comment]
I have created a WIP pull request: #12239 . However, this depends upon #11918 , so it must be merged first.
