### ISSUE TITLE
Global position is valid but still no home position is set at takeoff

### ISSUE THREAD

**Issue by DanielePettenuzzo** [PX4/Firmware#12204]
I had a couple flights in the last weeks where I did a takeoff in position mode and then tried to switch to mission using a switch on the rc and the mission was rejected. After looking at the log I noticed that it was rejected because no home position was set. The strange thing is that during takeoff my global position was already valid so I don't understand why my home position was not set. Anyone has any insights on why this might be happening?

Here is one of the logs I found to have this issue:
https://review.px4.io/plot_app?log=0974afe4-dadb-4a84-8633-7de483f4f0f8

I was flying a racer frame with a pixracer with both GPS and optical flow. The branch just had some minor unrelated things and was based on v1.9.0-beta.

**Comment by DanielePettenuzzo** [comment]
FYI @nicovanduijn

**Comment by nicovanduijn** [comment]
@ItsTimmy may have some additional logs of the same behavior occurring on the rover

**Comment by julianoes** [comment]
It looks like the GPS accuracy needs to be good enough for home to be set. Global position valid is not enough on its own:

https://github.com/PX4/Firmware/blob/be02ad3514213af7e1febd0377835eb00d063495/src/modules/commander/Commander.cpp#L1099-L1100

**Comment by bresch** [comment]
![2020-04-01_13-35-20_01_plot](https://user-images.githubusercontent.com/14822839/78132808-a76c7d00-741d-11ea-9d48-6e11cc39a332.png)
All the required conditions were good: eph, epv, condition_global_position_valid, condition_local_position so the only one that could have failed is the home position publisher.

We didn't see the issue since then so I this this got fixed. I'm closing it now, we can still reopen if needed.
