### ISSUE TITLE
I cannot get GPS Lock properly(No Green Light for GPS LED)

### ISSUE THREAD

**Issue by FlyingToTheSpace** [PX4/Firmware#12466]
Hello, I uploaded a issue #12438 few days ago and I found out what my problem is.

I'm using Pixhawk4 mini with Neo M8N GPS module.

First message I heard when I change flight mode from "Manual Mode" to "Hold Mode" is "REJECT AUTO HOLD"

So I wen through few tests, and I found out that GPS LED never shows flashing green light or solid green light which mean "Ready GPS" and "Armed GPS" respectively.

When I also disabled parameter for "Arming without GPS" , it says "Global Position Required" which I interpret that I don't get a proper GPS Signal.

Weird thing is I get GPS status really good. (18 statellites, HDOP: 0.7, VDOP: 1.3) and I see the position of my drone in map properly.

To fix it, I updated firmware which doesn't work.

I don't know any other solutions.

Please help me out

Thank you

**Comment by mcsauder** [comment]
@FlyingToTheSpace , have you left your drone out in the open for >30 min so that the M8N can really, truly get a lock, (powering it indoors can really mess up the position and take a long time to undo it's previous solution)? Perhaps we can move this topic from issues to https://discuss.px4.io/ to gather more help for you?
