### ISSUE TITLE
Possibly bug or just tradition?

### ISSUE THREAD

**Issue by hyonlim** [PX4/Firmware#12657]
**Describe the bug**
See above link. It is trying to swap x,y. Not z.

https://github.com/PX4/Firmware/blob/83e532d3399720b9bf10c2ed68adacd9ab4591a0/src/drivers/imu/mpu9250/mpu9250.cpp#L741

What is the purpose of this?

If you see another code, the intention of axes swapping is to make default sensor orientation (sensor on the PCB top, pin 1 toward west direction) to NED.
https://github.com/ArduPilot/ardupilot/blob/2a3676003aadf9fe3b2475b72e9687d77379e099/libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp#L424

This code is trying to make ENU (Invensense sensor default axis orientation) to NED (PX4 default axis)

Is this a bug or tradition? Because this makes unnecessary rotation happened during sensor acquisition. What do you think?

**Comment by mcsauder** [comment]
Hello @hyonlim , this was intentional due to legacy, [see comments above the line you linked](https://github.com/PX4/Firmware/blob/83e532d3399720b9bf10c2ed68adacd9ab4591a0/src/drivers/imu/mpu9250/mpu9250.cpp#L738).  the discussion in #9459 sheds a little bit of light:
![image](https://user-images.githubusercontent.com/2497951/62825478-70351d00-bb69-11e9-9596-4e3f530cc070.png)

X and Y were rotated 90, hence the Y negation.  Z axis remained with the same orientation.  Hopefully this helps clarify.  Good work combing through the code with an eye for possible errors!
