### ISSUE TITLE
Mavlink message for passing ALL IMU data

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#1269]
In the present implementation with the ROS bridge, we need to stream 2 types of mavlink messages (ATTITUDE and HIGHRES_IMU) for the full complement of IMU data (linear acceleration, angular velocity and orientation computed by AHRS)

Now, if we are streaming offboard at high rates (say for example 100hz) , it would be better to stream a single message at 100Hz rather than 2 separate messages at 100Hz each. This could be implemented as a option, not activated by default. 

I can do this, if we have a standard message for all the data in one go. @LorenzMeier What do you think?

Kabir

**Comment by psei0r** [comment]
Hi there guys!

I am currently building up a ROS-based rover using the PX4, so I found this posting doing some research. I managed to get the mavros bridge working and I am able to see the HIGHRES_IMU data for example. One of my questions was already answered by Lorenz, it was about the difference between ATTITUDE and HIGHRES_IMU, since we want the same as mhkabir, orientation AND IMU data in one message. 
My oder question is in general about the correspondencies between the mavlink streams , eg "HIGHRES_IMU" and the resulting published rostopics. Is there any documentation available which data is streamed in Mavlink under what data stream, and under which topic this will be published under ROS using mavros? The official docu of MAVLINK (https://pixhawk.ethz.ch/mavlink/)  is not very helpful to me at this place and I hope you can help me =)

best regards
Marcel

**Comment by psei0r** [comment]
I just found this one which covers nearly all of my questions : http://wiki.ros.org/mavros#Utility_commands

Thanks a lot guys, writing all this stuff down helped a lot :D

**Comment by nickhuan** [comment]
@mstuettgen @mhkabir hi guys, I just got a Qualcomm Snapdragon Flight and installed px4 Firmware onto it. May I know how you those IMU message ot HIGHRES_IMU data? as in which rosnode or roslaunch file I need to run to get those topics?

Thanks a lot
