### ISSUE TITLE
camera trigger parameters not appear

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#12699]
Hi

I can’t find trigger_mode parametrs and camera menue in qgc. i use pixhawk v2.4 

![image](https://user-images.githubusercontent.com/14200369/63027559-70fbe500-bec2-11e9-8144-d9e061429b3f.png)

**Comment by hamishwillee** [comment]
Usually when a parameter is missing in FMUv2 boards it means that the associated module is not in the firmware - many modules are disabled by default in Pixhawk FMUv2 boards because they don't have much memory.

The first thing you should try is updating your bootloader on the device to SEE if you can instead run FMUv3, which should include the necessary modules - see https://docs.px4.io/master/en/config/firmware.html#bootloader

If that does not work you would have to build the firmware yourself, enabling the module(s) needed. You might have to disable something else to allow it to fit. You can see where it is disabled here:
https://github.com/PX4/Firmware/blob/master/boards/px4/fmu-v2/default.cmake#L27
