### ISSUE TITLE
wind estimator 

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#12804]
Hi
we need to see wind speed and direction in flight for safety reasons.

![image](https://user-images.githubusercontent.com/14200369/63648684-838adf80-c748-11e9-8d1e-6f2c44079bf9.png)

**Comment by dagar** [comment]
Which version of PX4 are you using and how is it configured? Do you have a differential pressure sensor and the EKF2 airspeed fusion threshold set (EKF2_ARSP_THR)?

https://github.com/PX4/Firmware/blob/32fb4a958566c3855cab5b2e414b45d4f4dc9a65/ROMFS/px4fmu_common/init.d/rc.fw_defaults#L22-L31

**Comment by moreba1** [comment]
i used latest version of px4 with vtol deltaquad airframe reference . I use an airspeed sensor and actived it. EKF2_ARSP_THR was set to 0 (default) . do i have to change it to stall speed ?

**Comment by moreba1** [comment]
There is need documentation for wind estimation enabling .
does we can set maximum allowable wind speed for flight safety ?

**Comment by RomanBapst** [comment]
@moreba1 Can you share the log of that flight?

**Comment by moreba1** [comment]
https://review.px4.io/plot_app?log=b6146ff1-7a47-4259-a6ed-be9f05e1d172

**Comment by sfuhrer** [comment]
@moreba1 there is no "maximum allowable wind speed" preflight check, because wind estimation only starts in flight. 
For wind estimation to be active you need to set  EKF2_ARSP_THR to about 10m/s for your vehicle. Problem in your case: your airspeed sensor gives about 30% too low readings when compared to the ground velocity, so there won ever be a good wind estimate out of it. (as you mentioned in your issue https://github.com/PX4/Firmware/issues/12676)

Can you share a picture of where your airspeed sensor pitot is mounted? Maybe there's a problem there.
