### ISSUE TITLE
Benewake TFMini on GPS2 not working

### ISSUE THREAD

**Issue by M-J-Murray** [PX4/Firmware#13316]
**Describe the bug**
The online documentation for using the benewake tfmini rangefinder states that it should work on GPS2, however, after setting everything up, it doesn't work.

**To Reproduce**
1. Turn on Pixhawk2.1 Cube with fresh parameters
2. Choose Airframe Quadcopter x: Generic Quadcopter and reboot
3. Go to parameters and set 'SENS_TFMINI_CFG' to 'GPS 2', make sure benewake tfmini is connected to GPS 2 and reboot
4. Go to MAVLink Inspector and look for Distance Sensor

**Expected behavior**
The distance sensor message data should appear, however, no distance sensor message data appears

**Log Files and Screenshots**
Attached

**Comment by M-J-Murray** [comment]
I've narrowed down the issue. The problem is that the tfmini service is not starting when the 'SENS_TFMINI_CFG' is configured to 'GPS 2'. If I run the command 'tfmini start -d /dev/ttyS6' in the QGroundControl console, then the distance sensor messages start appearing.

**Comment by M-J-Murray** [comment]
You probably just need to add 'GPS2:/dev/ttyS6' to the 'SERIAL_PORTS' in the 'defaults.cmake'

**Comment by mcsauder** [comment]
Hi @M-J-Murray .  Thanks for the additional information. I think that the reason for this might be that GPS2 for fmu-v3 might not be called out correctly in the default.cmake file: https://github.com/PX4/Firmware/blob/66b3a4269b33042d628644ee4b01b33734e96ffc/boards/px4/fmu-v3/default.cmake#L17

Perhaps you could verify that for me by adding `GPS2:/dev/ttyS6` and building/flashing to see if that solves your issue. If that solves it, perhaps we can follow up with a PR.  (I'd test myself but I don't have hardware.)

**Comment by mcsauder** [comment]
Looks like we are thinking along the same lines. :)

**Comment by M-J-Murray** [comment]
I received the email. I've just attempted the flash a couple times but I keep getting the following error: "Error: Flash failed: Command failed: 0x13 (PROTO_INVALID) at address 0x0019b900".
Any idea?

**Comment by mcsauder** [comment]
Perhaps it is this: https://github.com/PX4/Bootloader/issues/43
I'll follow up with you over email or slack until we can figure it out!  Thanks for testing so quickly.

**Comment by M-J-Murray** [comment]
I made the same change to the "v1.9.2" tag branch, built and flashed and now it is working.

**Comment by mcsauder** [comment]
Hi @M-J-Murray , we discussed this issue on the dev-call this morning and the concern is that only the 2.1 Cube has a port labeled `GPS2`, none of the other fmu-v2/v3 variants have a dedicated (labeled) GPS2 port. For the Cube, GPS2 is the ttyS4 UART port, and `TEL4` is defined as such, (`/dev/ttyS6`). To allow your setup to function, instead of selecting `GPS2` in QGC, select  `TEL4` we will update the documentation to reflect this unique case.

Also, not mentioned in the discussion above but in our side conversation, you might need to update your bootloader firmware: https://docs.px4.io/v1.9.0/en/advanced_config/bootloader_update.html.

Hi @hamishwillee , could I connect with you to help me update the docs to reflect that the GPS2 port on Cube 2.1 should be treated as TEL4?

**Comment by hamishwillee** [comment]
@mcsauder Sure!
So just to confirm, the problem is that there is a port labeled GPS2 on the Cube, but this physical port is actually mapped to TEL4 by Pixhawk? So people should connect to GPS2 port and set SENS_TFMINI_CFG to TEL4, or connect to whatever is the "ttyS4 UART" port and then select GPS2?

1. Is this irrespective of PX4 version? Note, we tend to update master, not every single version.
2. I assume we can't remap the serial ports so the label and the port correspond?

Not quite sure where best places to document are. Some options:
* [Cube Quickstart > Wiring guide](https://docs.px4.io/master/en/assembly/quick_start_cube.html#wiring-overview) - maybe note end here.
* [Hex Cube > Ports](https://docs.px4.io/master/en/flight_controller/pixhawk-2.html#ports) - definitively a note here.

While it would be "most useful" to add this note in individual docs - e.g the one for TFMini, I don't want to add this sort of thing everywhere. People should be able to rely on FC screen printing.

**Comment by mcsauder** [comment]
Thanks @hamishwillee !

Yes, the port labeled `GPS2`, which exists on the cube only and no other fmu-v2/v3 hardware, maps to `ttyS4`, which is `TEL4` on all of the other fmu-v2/v3 autopilots, (to the extent of my knowledge and digging around).

> 1. Is this irrespective of PX4 version? Note, we tend to update master, not every single version.
This only affects the Cube autopilots, so it only affects v2/v3 firmware, but yes, it is the same in v1.82, v1.9.2, v1.10...  I believe it would be sufficient to simply update the docs for v1.10 since this has gone unnoticed for so long.
> 2. I assume we can't remap the serial ports so the label and the port correspond?
This is what I had thought in PR #13322, but the consensus is that if a user selects one device mapped to GPS2 and another device to TEL4 it would be a worse outcome than leaving as-is and updating the docs to raise some awareness.

I think it belongs only with the Cube documentation as you indicated, because that is the only hardware with a `GPS2` (ttyS6) labeled port.  I think adding a UART port description as well might be useful.  From the `fmu-v2/v3 default.cmake` files: 
```
	SERIAL_PORTS
		GPS1:/dev/ttyS3
		TEL1:/dev/ttyS1
		TEL2:/dev/ttyS2
		TEL4:/dev/ttyS6
```
> While it would be "most useful" to add this note in individual docs - e.g the one for TFMini, I don't want to add this sort of thing everywhere.
I think the reason not to put it with individual sensors is that we would have to do that for all serial devices.  Best left with the Cube docs because it is the only hardware with that particular issue.

Thank you for your reply!

**Comment by hamishwillee** [comment]
Merging!
