### ISSUE TITLE
Violent jerk when switching from manual to position mode

### ISSUE THREAD

**Issue by dakejahl** [PX4/Firmware#13415]
**Firmware**: 1.9.2 (with #13312 and #13325)

**Describe the bug**
I'm seeing huge pitch/roll setpoints when switching from manual to position mode . It seems like it's the velocity controller, but I don't really understand how the velocity controller ends up demanding such large effort of the attitude controller. I've detuned the P gain on the velocity controller and am still seeing a violent jerk when switching from manual to position. Here's a log with 3 mode switch, the first one being the most violent.

**To Reproduce**
1. Switch from `manual` to `position` mode. The more velocity you have before the switch, the more violent the jerk.

**Log Files and Screenshots**
https://review.px4.io/plot_app?log=4fa7056e-d1bc-437f-829d-0b45e3087276
![Selection_038](https://user-images.githubusercontent.com/37091262/68419559-afb6d980-0157-11ea-96b3-72665d0f29f1.png)
![Selection_041](https://user-images.githubusercontent.com/37091262/68419888-5307ee80-0158-11ea-93d5-1dddd621be10.png)

The velocity setpoints are not changing dramatically, so the attitude effort should not be there.
![Selection_039](https://user-images.githubusercontent.com/37091262/68419561-b1809d00-0157-11ea-9cd0-991be8fbca65.png)

@bresch @mhkabir @TSC21 

Related to #12389

**Comment by mhkabir** [comment]
Any chance you can try v1.10?

**Comment by bresch** [comment]
@mhkabir  It's also on master. I found out that the problem is in the initialization of the velocity controller, check on the following graph, the difference between a transition from stabilized -> position and altitude -> position:
![2019-11-18_13-49-06_01_plot](https://user-images.githubusercontent.com/14822839/69054027-056a6c00-0a0b-11ea-8a5b-e830b045c9f0.png)
The Z thrust (thrust[1]) initializes at a high value.
After discussing with @MaEtUgR , he remembered that the numerical derivative used in the D-term of the velocity controller could be badly initialized.

I then ran a new simulation with the D gain set to 0 and there is no glitch anymore:
![2019-11-18_13-53-08_01_plot](https://user-images.githubusercontent.com/14822839/69054298-8c1f4900-0a0b-11ea-80e0-0d67a531cafe.png)

@MaEtUgR Is already working on the refactoring of the position controller and will make a PR asap. I think we should also backport this fix in v1.10
