### ISSUE TITLE
Add param for enabling/disabling estimate sources [inav]

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#1359]
Since there are use-cases where we are using complete offboard fusion of positional data from multiple source, it would be useful to be able to turn off usage of different sources in inav.

For example, in ROS, I'm using GPS data from the PX4 and fusing it in an EKF together with two more visual estimate sources. In this case, I want my local estimate to come only from offboard and not inav's extra fusion. Inav will only use the stream from ROS as the only source (already has all sources fused)

I would like to use the navigation features of GPS in the flight stack though, without using it for local estimates. I'm not sure how GPS navigation works here, but ideally, I would like to use the navigation/waypoint features without fusing GPS into inav.

@LorenzMeier Comments?
@DrTon What do you think?

**Comment by thedinuka** [comment]
I think it's worth keeping the position and velocity prediction based on inertial sensors, first to improve the GPS and or vision estimates and second to act as backup between GPS/Vision outages. However, I also think that there are a few problems in the inertial prediction stages of [inav].

On a a related question, is someone actively maintaining [inav] or is it not being used that much these days?

**Comment by DrTon** [comment]
Actually you can simply set INAV_W_XY_GPS_P and it will be completely ignored. If you add some offboard estimate source to inav you can use inav just for filling the gaps between offboard data frames. Estimate will be more fast, and still very close to offboard estimate.

Inav still used as default position estimator for copters and works nice. But code is really very old and must be rewritten. IMO it should be left in codebase anyway, at least as optional solution, because it's much more easy to hack and extend than heavy EKF.

**Comment by LorenzMeier** [comment]
Implemented as INAV_ENABLED.
