### ISSUE TITLE
mpc: states.acceleration has wrong sign

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#13887]
Looking at the acceleration states in the mc position controller it seems to me that they have the wrong sign
https://github.com/PX4/Firmware/blob/92adc5afaa9a1bf8776f8764374fb54ac6b48d38/src/modules/mc_pos_control/mc_pos_control_main.cpp#L453-L453

I.e. they are actually the negative of the acceleration. Is this intended or should I change it?

**Comment by dagar** [comment]
> I.e. they are actually the negative of the acceleration. Is this intended or should I change it?

I'm curious as well.

While we're on the subject I also really don't like that the acceleration actually used by the controller isn't logged. (https://github.com/PX4/Firmware/pull/13527)

**Comment by bresch** [comment]
Yes, the sign of the acceleration is wrong, but the result is correct, because in the velocity controller, we do `output = vel_error * P + vel_error_int * I + acceleration * D` (normally, we should put the minus sign here)

**Comment by MaEtUgR** [comment]
@CarlOlsson Yes, you're completely right in the sense that the sign is wrong for the variable name and that's totally confusing and we should change that. It's only used in the position controller as `vel_dot` https://github.com/PX4/Firmware/blob/0a2c48c69aabbcb9a290098bc324ef1872d87125/src/modules/mc_pos_control/PositionControl/PositionControl.cpp#L148 and it's used for the derivative term of the velocity control like an error which requires a sign switch and that's why it's the negative state here.

All correct calculation but totally confusing and we need to immediately change it. I'll open a pr.

**Comment by MaEtUgR** [comment]
I changed it here: https://github.com/PX4/Firmware/pull/14629
