### ISSUE TITLE
CPU intensity of uavcan driver

### ISSUE THREAD

**Issue by hsteinhaus** [PX4/Firmware#1417]
Without any peripherals connected, the uavcan process seems to consume at least 15% of available CPU power on Pixhawk (latest PX4/Firmware master with APM master build). This is rather nasty, as the uavcan process runs with a high priority. After connecting UAVCAN components, there is only a marginal increase (to about 20%). May be a fast spinning loop somewhere?

**Comment by LorenzMeier** [comment]
@hsteinhaus @pavel-kirienko Have we worked out the issue here?

**Comment by hsteinhaus** [comment]
The last time I checked the CPU load (early December) the issue was still present. 

May be this is related: https://groups.google.com/forum/#!msg/drones-
discuss/qJ7aQK2GQ18/xWc_KfoL0PkJ

**Comment by pavel-kirienko** [comment]
@LorenzMeier I'm on it now.

**Comment by pavel-kirienko** [comment]
I added some perfcounters, see https://github.com/PX4/Firmware/commit/7bf226abaf9ece7af38a72a3f9bfe108c8961912.

This is what I got after 360 sec uptime:

```
uavcan_esc_mixer_subscriptions: 1 events
uavcan_esc_mixer_total_elapsed: 88700 events, 38033097us elapsed, 428us avg, min 110us max 1214us
uavcan_esc_mixer_output_elapsed: 88678 events, 19649356us elapsed, 221us avg, min 9us max 849us
uavcan_node_spin_elapsed: 88719 events, 11672391us elapsed, 131us avg, min 85us max 700us
uavcan_esc_scaling_error: 0 events
uavcan_esc_invalid_input: 0 events
```

Where:
* `uavcan_esc_mixer_total_elapsed` - total wall time of the driver loop, measured between poll() calls;
* `uavcan_esc_mixer_output_elapsed` - wall time spent inside [UavcanEscController::update_outputs()](https://github.com/PX4/Firmware/blob/master/src/modules/uavcan/actuators/esc.cpp#L77);
* `uavcan_node_spin_elapsed` - wall time spent inside uavcan::Node::spin().

Conclusions so far:
* poll() unblocking rate is ~250 Hz, as expected. This concurs with my observation shared [here](https://groups.google.com/d/msg/drones-discuss/qJ7aQK2GQ18/mpv-We0MH6AJ). This means that there's no tight loop.
* Most of the CPU time is spent inside `UavcanEscController::update_outputs()`. Most likely, the top spender is this [unaligned bit array copy routine](https://github.com/UAVCAN/uavcan/blob/master/libuavcan/src/marshal/uc_bit_array_copy.cpp#L27).
* uavcan::Node::spin() gets called more often than necessary. This can be fixed easily, but it won't reduce CPU load significantly.

According to the perfcounters, actual mixing takes about 428-221-131=76 microseconds per iteration on average, such load is quite insignificant.

I tried to compile entire uavcan module and libuavcan with `-O3` instead of currently used `-Os`, but this didn't help much - CPU load decreased just by 3%.

> Additionally, the load seems not follow to the update rate of published objects (tried 150..490Hz).

This can be explained by the fact that `UavcanEscController::update_outputs()` is rate-limited at 200 Hz.

---

I think I'll need to profile the entire libuavcan message publication call chain to find out what exactly takes so much time. @LorenzMeier, we don't have a profiler for NuttX, do we?

**Comment by pavel-kirienko** [comment]
I'm still on it, here's an intermediate update. My assumption that the problem is in the bit array copy routine does not seem correct.

I somehow adapted the poor man's sampling profiler for NuttX ([here](https://github.com/PX4/Firmware/blob/uavcan_cpu_usage_investigation/Debug/poor-mans-profiler.sh)) and added conversion to FlameGraphs. This is what I saw:

![png](https://cloud.githubusercontent.com/assets/3298404/5750514/197edea4-9c67-11e4-9bbe-db5705ceb978.png)

Most of the time is spent inside a service routine that cleans up some temporary objects, and somewhere inside Node::spin(). The last one is suspicious - the code of this method is literally just:

```c++
    int spin(MonotonicTime deadline)
    {
        return getScheduler().spin(deadline);
    }
```

Seems like some debug information is missing.

**Comment by pavel-kirienko** [comment]
Turns out that the Nuttx.py script doesn't recover call stacks correctly, so I ended up sampling entire system using gdb's command `bt`, and I found something interesting.

First, I modified the firmware so there was virtually just uavcan process left, and it was just sending frames in a tight loop, producing CPU load around 97%. I sampled it, and this was the result: https://yadi.sk/d/dVtTeGyee3zHB (it's an interactive SVG, make sure to open it in a web browser). Upon careful review I found it alarming that, apparently, compiler has failed to eliminate or inline some functions. Here's a short list of the functions that looked particularly wrong:

- `uavcan::LinkedListNode<uavcan::CanTxQueue::Entry>::getNextListNode()` - must be inlined, it's plain getter
- `uavcan::StaticAssert<true>::check()` - must be eliminated, it's empty
- `uavcan::MonotonicTime::~MonotonicTime` - empty
- etc., the list goes on.

Further review revealed that there's a lot of calls to the profiling instrumentation functions `__cyg_profile_func_enter()` and `__cyg_profile_func_exit()`. It seems like in NuttX these functions are leveraged for stack overflow checks. Since these functions are called every time the application enters and leaves a function context, I assumed that impact on the performance of libuavcan would be particularly strong due to its design (average function length in libuavcan is quite short, e.g. it makes a lot of calls, and there are some functions (see above) that were designed with expectation that they will be inlined or eliminated by the compiler). In order to check this assumption, I made a list of most common functions that end up on the top of call stacks - this allowed me to roughly evaluate their contribution to the system load. The results look horrifying (this is just top ten functions):

```
 21.6%    __cyg_profile_func_enter
 10.5%    uavcan::LinkedListNode<uavcan::CanTxQueue::Entry>::getNextListNode
  3.4%    uavcan::LinkedListRoot<uavcan::CanTxQueue::Entry>::remove
  3.1%    uavcan::StaticAssert<true>::check
  3.1%    __cyg_profile_func_exit
  2.5%    uavcan::LinkedListRoot<uavcan::CanTxQueue::Entry>::insertBefore<uavcan::CanTxQueue::PriorityInsertionComparator>
  2.4%    uavcan::MonotonicTime::~MonotonicTime
  2.0%    uavcan::CanFrame::priorityHigherThan
  1.9%    uavcan::CanTxQueue::PriorityInsertionComparator::operator()
  1.7%    uavcan::TimeBase<uavcan::MonotonicTime, uavcan::MonotonicDuration>::~TimeBase
```

This adds up to at least ~42% of CPU time spent on checking for stack overflows. I want to note again that it hits libuavcan especially hard due to its design (it makes many calls to short or empty functions).

At this point it was clear to me that the libuavcan on NuttX just isn't compatible with `-finstrument-functions` (this is the flag that enables calls to `__cyg_profile_*()`). Before continuing with disabling this flag, I decided to run the whole system in its default configuration (with UAVCAN ESC mixer enabled) under the profiler for several hours. This is the resulting flame graph: https://yadi.sk/d/JwbsArFte43HX (again, open it in the browser); here's top ten CPU time spenders:

```
 15.3%    __cyg_profile_func_enter
  9.9%    up_idle
  9.1%    AttitudeEKF
  3.3%    spi_getreg
  2.9%    __cyg_profile_func_exit
  2.8%    getreg16
  1.7%    os_start
  1.7%    hrt_absolute_time
  1.4%    mrdivide
  1.2%    spi_readword
```

As can be seen, profiling instrumentation amounts to a rediculously high load again. For reference, this is what `top` looked like in this test:

```
Processes: 21 total, 4 running, 17 sleeping
CPU usage: 76.01% tasks, 0.70% sched, 23.29% idle
Uptime: 27.724s total, 7.452s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE
   0 Idle Task                    7452 23.286     0/    0   0 (  0)  READY
   1 hpwork                        465  1.791   612/ 1992 192 (192)  w:sig
   2 lpwork                        206  0.778   612/ 1992  50 ( 50)  READY
   3 init                         1658  0.000  1636/ 2992 100 (100)  w:sem
   6 nshterm                         1  0.000   772/ 1592  70 ( 70)  w:sem
 147 top                           491  2.959  1276/ 1696 100 (100)  RUN
  59 dataman                        70  0.000   748/ 1992 100 (100)  w:sem
  61 commander                     266  0.467  2668/ 3192 215 (215)  w:sig
  62 commander_low_prio             11  0.000   564/ 2896  50 ( 50)  w:sem
  69 px4io                        1739  6.853   824/ 1992 240 (240)  w:sem
  79 mavlink_if0                   469  1.869  1876/ 2792 100 (100)  w:sig
  80 mavlink_rcv_if0                 4  0.000   852/ 2896 175 (175)  w:sem
  85 uavcan                       3423 14.485  1388/ 2992 240 (240)  w:sem
 116 sensors_task                 1635  6.775  1220/ 1992 250 (250)  w:sem
 136 attitude_estimator_ekf       5941 24.844  6460/ 7696 250 (250)  w:sem
 121 sdlog2                        206  0.700  2156/ 2992  70 ( 70)  READY
 124 gps                            86  0.545   764/ 1496 220 (220)  w:sem
 138 position_estimator_inav       914  3.971  4236/ 4992 250 (250)  w:sem
 140 mc_att_control               1632  6.775  1128/ 1992 250 (250)  w:sem
 142 mc_pos_control                238  1.090  1084/ 1992 250 (250)  w:sem
 146 navigator                     523  2.102   932/ 1792 120 (120)  w:sem
```

Then I disabled the instrumentation [here](https://github.com/PX4/Firmware/blob/uavcan_cpu_usage_investigation/makefiles/toolchain_gnu-arm-eabi.mk#L83) and re-run everything. Flamegraph: https://yadi.sk/d/3s7pE3Tre43Wg; top spenders:

```
 16.9%    up_idle
 15.6%    __cyg_profile_func_enter
  8.5%    AttitudeEKF
  3.7%    spi_getreg
  3.3%    os_start
  3.0%    __cyg_profile_func_exit
  2.7%    getreg16
  1.4%    mrdivide
  1.3%    spi_readword
  1.3%    hrt_absolute_time
```

`__cyg_profile_*()` is still here, probably it's getting called from the OS, but CPU load has dropped dramatically:

```
Processes: 21 total, 2 running, 19 sleeping
CPU usage: 56.72% tasks, 0.86% sched, 42.42% idle
Uptime: 2458.729s total, 1109.687s idle

 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE
   0 Idle Task                 1109687 42.419     0/    0   0 (  0)  READY
   1 hpwork                      43055  1.728   612/ 1992 192 (192)  w:sig
   2 lpwork                      20729  0.864   612/ 1992  50 ( 50)  READY
   3 init                         1653  0.000  1628/ 2992 100 (100)  w:sem
   6 nshterm                         1  0.000   716/ 1592  70 ( 70)  w:sem
 136 attitude_estimator_ekf     564502 22.545  6252/ 7696 250 (250)  w:sem
  59 dataman                        66  0.000   732/ 1992 100 (100)  w:sem
  61 commander                    7547  0.235  2636/ 3192 215 (215)  w:sig
  62 commander_low_prio            807  0.000   548/ 2896  50 ( 50)  w:sem
  69 px4io                      145154  5.734   784/ 1992 240 (240)  w:sem
  79 mavlink_if0                 28227  1.099  1964/ 2792 100 (100)  w:sig
  80 mavlink_rcv_if0               589  0.000   860/ 2896 175 (175)  w:sem
  85 uavcan                     134354  5.498   988/ 2992 240 (240)  w:sem
 116 sensors_task               119378  4.556  1140/ 1992 250 (250)  w:sem
 150 top                           279  3.692  1284/ 1696 100 (100)  RUN
 121 sdlog2                      15945  0.628  2012/ 2992  70 ( 70)  w:sig
 124 gps                          9910  0.078   772/ 1496 220 (220)  w:sem
 138 position_estimator_inav     80253  3.220  4188/ 4992 250 (250)  w:sem
 140 mc_att_control             108059  4.399  1220/ 1992 250 (250)  w:sem
 142 mc_pos_control              22814  0.785  1052/ 1992 250 (250)  w:sem
 146 navigator                   44922  1.649   852/ 1792 120 (120)  w:sem
```

Notice ~60% CPU load drop in the uavcan process, and overall CPU usage reduction from 76% to 57%.

I tried to disable instrumentation for the uavcan module only by adding a flag `-fno-instrument-functions`, but it didn't work - probably it's getting overriden by the global flag.

## Conclusion

- Stack overflow checks in `__cyg_profile_*()` amount to ~19% of the overall CPU load.
- Stack overflow checks in `__cyg_profile_*()` amount to ~60% of the CPU load of the uavcan process, due to its design (short/empty functions).
- uavcan process doesn't have any distinguished performance issues - when the instrumentation is disabled, the CPU time spent inside libuavcan is actually lower than in `poll()`. Nevertheless, I found some ways how to further optimize it.
- Disabling instrumentation causes the firmware image file to reduce considerably, thus is can be possible to enable `-O3` for the uavcan module, which may further improve performance.

## Suggestion

- Instrumentation for the uavcan module must be disabled.
- uavcan module can be compiled with `-O3`.
- Probably, the existing stack overflow check strategy needs to be reviewed.

**Comment by LorenzMeier** [comment]
@pavel-kirienko On an autopilot safety comes first. We are fully aware of the performance implications of stack checking, but without a proper MPU its the only safety guard in place to detect failures, and it has saved us a few times already. Without stack checking, stack overflows are much harder to trace back. However, for release binaries there is less motivation to have it still enabled, and so we could constrain make it a build option on the command line.

**Comment by pavel-kirienko** [comment]
OK, I'll disable it only for uavcan then, and then look if it's possible to use `-O3`. Any suggestion on what is the best way to disable it? As I said above, adding `-fno-instrument-functions` to the module.mk doesn't help.

Also, you said that the instrumentation is disabled in the branch nuttx_bringup, why?

**Comment by pavel-kirienko** [comment]
Binary sizes in different builds:

- current master: 993K
- instrumentation disabled: 774K
- instrumentation disabled, uavcan with `-O3`: 787K

**Comment by pavel-kirienko** [comment]
The last configuration (-O3) doesn't reduce uavcan CPU usage significantly though - still around 5.2%.

**Comment by pavel-kirienko** [comment]
It has been confirmed that the root cause of the issue are excessive stack overflow checks and not the UAVCAN driver itself, so I'm closing it. Further discussion is in https://github.com/PX4/Firmware/pull/1660
