### ISSUE TITLE
fmu-v3 secondary baro missing

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#14522]

**Comment by OskarPepryk** [comment]
I can confirm this, on two of Cubes i have tested, second barometer is detected as MS5607 and gives  wrong readings. 
![Zrzut ekranu z 2020-05-08 08-30-01](https://user-images.githubusercontent.com/23101737/81377807-80812500-9106-11ea-99de-ce499d9232ee.png)
AFAIK 2 baros on boards are both MS5611, so perhaps the problem would be fixed by just altering the startup code.

Problem is present on master and v1.11.0 Beta 1

**Comment by dagar** [comment]
I believe the missing start was added and the incorrect detection is now a new issue.

**Comment by dagar** [comment]
This has been fixed.
