### ISSUE TITLE
Linux Boards 

### ISSUE THREAD

**Issue by bilginmu** [PX4/Firmware#14697]
Is there any documantation about that how to run PX4 on linux boards ?

**Comment by bilginmu** [comment]
I have Arm microprocessors Cortex-A9 on which is running real time linux.

**Comment by hamishwillee** [comment]
Yes, see 
- https://dev.px4.io/master/en/setup/building_px4.html#raspberry-pi-23-boards
- https://dev.px4.io/master/en/setup/dev_env_linux_ubuntu.html#raspberry-pi-hardware

I am closing this because this area is for issues/bugs, not support requests. If you wish to continue the discussion, please raise on https://discuss.px4.io/ (cross linking to here)

**Comment by bilginmu** [comment]
Sorry for wrong area and thanks for reply but I have Petalinux and how to build for petalinux? Building px4 for petalinux and rasperry pi are the the same ?
