### ISSUE TITLE
v1.11 reset icm20689 accel calibration? 

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#14777]
With the new icm20689 the ~~scale factor~~ offset comes out close to 0. Existing setups calibrated with PX4 v1.10 (the mpu6000 driver) seem to have an offset on one axis that's nearly 2.

This is a bit hacky, but at param import time we can identify this in the parameters and reset the offset if it exists only on one axis and exceeds some arbitrary value.

FYI @MaEtUgR

**Comment by MaEtUgR** [comment]
@dagar I didn't see a scale of 2 in my cases. Is that a different issue?

I was reporting the case where I had to recalibrate the accelerometer on both vehicles that had a Firmware older than 2 months ago and I updated to master. I recalibrated because both vehicles showed a steep pitch angle when completely level in the attitude estimate represented by QGC's virtual horizon after updating.

The quadrotor uses a pixhawk 4 mini
The plane uses a pixhawk 4

| | quad before | quad after | plane before | plane after |
|---|---|---|---|---|
| CAL_ACC0_ID | 3932170 | 3932170 | 3866634 | 3932170 |
| CAL_ACC0_XOFF | 1.581990 | -0.173167 | -2.507170 | -0.041409 |
| CAL_ACC0_XSCALE | 0.932632 | 1.001169 | 0.925561 | 0.999273 |
| CAL_ACC0_YOFF | 0.150241 | 0.251485 | 0.071872 | 0.041645 |
| CAL_ACC0_YSCALE | 0.997267 | 0.999228 | 1.003336 | 0.985294 |
| CAL_ACC0_ZOFF | -0.238199 | -0.227139 | -0.043277 | 0.089027 |
| CAL_ACC0_ZSCALE | 0.987909 | 0.985522 | 0.984737 | 0.978124 |

These are always the primary accelerometers and what I see is a clear change in x-axis offset which would also explain the pitch error. I do not know how the same calibration was considered perfectly level before since I flew both platforms a lot without issues or need to recalibrate the accel.

As a solution to the offset problem I only see recalibration. Maybe it would have not even armed because of consistency checks but I didn't dare to try.

**Comment by dagar** [comment]
The root cause appears to be this undocumented register applied to ICM devices in the old mpu6000 driver. This mpu6000 driver was used for the mpu6000, icm20602, icm20608g, icm20689 up until recently.

https://github.com/PX4/Firmware/blob/ccaa103164a09d66ff9faf4fcdfb39a09ba834a1/src/drivers/imu/mpu6000/MPU6000.cpp#L194

**Comment by dagar** [comment]
I think the only question then is if we force recalibration of everything if the offset is this bad or can we get away with only clearing the single offset under the right conditions.

**Comment by bys1123** [comment]
Maybe we should add a parameter storage what version firmware been used in previous bootup. Then with some mapping work the program could know what initialize progress it should do after firmware update.

**Comment by bys1123** [comment]
If not, I guess we would reset recalibration everytime after firmware update in the future?

**Comment by bys1123** [comment]
After upgrade to 1.11, pre-flight check will tell users accel inconsistent, so may not cause un-safety?

**Comment by dagar** [comment]
> After upgrade to 1.11, pre-flight check will tell users accel inconsistent, so may not cause un-safety?

Yes, so this is more about trying to make the upgrade experience less unpleasant.

**Comment by bys1123** [comment]
I flash back to 1.10, shows accel is uncalibrated.

**Comment by dagar** [comment]
I've decided to leave it alone. If the offset is sufficiently different and beyond the estimator bias limits you'll be unable to arm until you recalibrate.

This is a good reminder that we should be a bit more discerning before letting undocumented magic fixes slip into the code base. https://github.com/PX4/Firmware/blob/6afa7e4368c4bb925b298f2f50aa3c50cdebdf71/src/drivers/imu/mpu6000/MPU6000.cpp#L666-L669
