### ISSUE TITLE
SITL: Logger is missing samples of ekf2_timestamps

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#15088]
When running SITL and adding a counter to the ekf2_timestamps topic we realized that not all the samples are logged. The logger does not report and dropouts though.
I went back to v1.9.2 and still saw the same behavior.
We are thinking that this might be the reason why replay on SITL logs is not working well.

![image](https://user-images.githubusercontent.com/7610489/84365818-ad7b9880-abda-11ea-9233-e82888a88834.png)

**Comment by julianoes** [comment]
I think the problem is that lockstep only waits for data ready to be sent to the simulator, so the actuator_controls essentially. However, it doesn't wait until logger is done logging everything.

We could think of adding some sort of flag for logger to signal that it is done writing things to disk, so that we can continue with lockstep.

**Comment by bkueng** [comment]
Yes we need to integrate the logger into the lockstep cycle to solve this cleanly.

However a quick test showed that also letting logger poll on `ekf2_timestamps` improves things a lot already.
