### ISSUE TITLE
Multirotor auto takeoff without takeoff waypoint can fail

### ISSUE THREAD

**Issue by sjwilks** [PX4/Firmware#1789]
If an auto takeoff is performed and the next waypoint in the mission is not a takeoff waypoint the multirotor tries to fly directly to the waypoint on takeoff rather than first climbing vertically to a safe height. This usually results in a failed launch as the multirotor tilts towards the waypoint.

**Comment by thomasgubler** [comment]
Makes me wonder if we should get rid of the takeoff wp altogether? (At least for multicopters).

**Comment by sjwilks** [comment]
True. I can't think of anything at the moment that a takeoff waypoint would
do differently now or in the future.

**Comment by tumbili** [comment]
@sjwilks @thomasgubler @LorenzMeier Is this an error?
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L452
I assume that altitudes are expressed in the NED frame? This would explain why the take-off to a save altitude is skipped.

**Comment by LorenzMeier** [comment]
See here:
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission.cpp#L438-L441

What is intriguing though is that in that line we're using the acceptance radius, which is param NAV_ACC_RAD, which defaults to 2 meters if the vehicle was set up using auto-config steps.

The radius is the error allowed in 3D, so at the very least we need to take e.g. 1/3 to represent that this is now just in Z. Since this is an initial check I would even go as far to say that the radius should be deleted at this particular position.

**Comment by LorenzMeier** [comment]
@sjwilks You will want to check our NAV_ACC_RAD value.

**Comment by thomasgubler** [comment]
I would also vote for removing the radius in this case.

**Comment by LorenzMeier** [comment]
@sjwilks Let us know if it persists, assuming this to be closed for now.
