### ISSUE TITLE
Evaluate att_post_estimator_ekf performance

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#1902]
@Zefz and I noticed that the overall performance degraded with the latest bugfixes. The current state needs to be carefully analyzed again on the test bench.

Another log to look at is this one:
http://dash.oznet.ch/view/u4eKwNr8ziKVDUXmwJo933#Thrust_PLOT

**Comment by Zefz** [comment]
Quoting myself from chat:

Perhaps the issue is in AttPosEKF::ResetPosition() which does not reset covariance values for position
Previously when the filter accepted reset position estimate after rejection, it reset a lot of the filter and cleared much data (causing the sudden jump glitch on GPS regain among other things). Perhaps some of the data clearing/reset (like covariance) need to be added back in

**Comment by Zefz** [comment]
#1913 and #1919 seem to have resolved the major EKF issues we were experiencing. Is the filtering performance still degraded?

**Comment by LorenzMeier** [comment]
Yes, we're almost there. I would love to have another look at the Z estimation performance, since the filter output should be better than what the baro provides.

**Comment by Zefz** [comment]
According to this post in the mailing list the Z estimation still has some issues:
https://groups.google.com/forum/#!topic/px4users/Jur7I82lVcg

Here is some log data using EKF:
http://dash.oznet.ch/view/QHbHZsgPoixbWhcbxYVUoj

Notice that altitude estimations has clearly some oscillations that are induced by the filter itself.

Compare this with flying the same quad using the INAV filter:
http://dash.oznet.ch/view/DF8S3URq88sB8SfHucpZ49#Local_Z_PLOT

**Comment by LorenzMeier** [comment]
Doing that, moving to EKF2
