### ISSUE TITLE
Implement POSCTL for fixed wing

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2022]
Currently position control is not yet implemented yet for fixed wing planes.
In this mode the plane will fly along a straight line at certain altitude. The user can use the roll stick to change the orientation of this line and thus influence the heading of the plane. The user can also command climb/descent rate with the pitch stick and speed with the throttle stick. This can be useful for FPV flying.

**Comment by severinleuenberger** [comment]
This makes sense, to have the heading implemented as well. 
It would be cool, when most of the yaw correction for heading-hold triggered by the PX4 FC would lead to an rudder-actuator movement and not a correction by ailerons. This would make the flying smoother and more near to real aircrafts. If rudder doesnt response enough (because there is no rudder), only then a aileron actuator should add for a roll movement.
