### ISSUE TITLE
GPS driver keeps publishing even when GPS isn't connected

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#2551]
When no GPS is connected, the driver still keeps spamming the topic with empty messages. Driver in Ashtech mode when this occurs.

Running a UAVCAN-interfaced GPS in parallel then causes weird issues.

@kd0aij Also brought this up.

**Comment by LorenzMeier** [comment]
Indeed, we need to fix that. I don't recall why this would be necessary.

**Comment by LorenzMeier** [comment]
@Zefz I think you introduced this, but I don't recall what the use case was.

**Comment by Zefz** [comment]
@LorenzMeier My GPS check only runs if you have the circuit breaker is disabled (CBRK_GPSFAIL). It is on by default so unless you explicitly requested it, the Preflight GPS check will not run.

My preflight check is here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/PreflightCheck.cpp#L277-L305

This is not the same as messages coming from the GPS driver as @mhkabir is mentioning?

@LorenzMeier Use case: Detect faulty GPS wiring, broken GPS receiver or GPS receivers that are placed too close to the RC receiver (which will kill all reception because of the noise). Without this check the system does not report anything wrong - it will simply never get a fix :)

**Comment by LorenzMeier** [comment]
Its the ashtech driver which returns success for no reason:
https://github.com/PX4/Firmware/blob/master/src/drivers/gps/ashtech.cpp#L647-L661

**Comment by LorenzMeier** [comment]
Closed in d9f0baf on beta.
