### ISSUE TITLE
Implement stick mapper work queue

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2822]
The goal is to remove any non-control related attitude setpoint generation code out of the control modules. E.g. at the moment attitude setpoints in manual mode are generated in mc_pos_control and fw_att_control.
The idea is to create a stick mapper function which is implemented as a work queue in order to save stack size. This function should map manual control inputs from the user to attitude setpoints for the attitude controllers.
For the multicopter case this is straight forward because in every mode the attitude setpoint is either published by the position controller or by the stick mapper function.
For the fixed wing case this is a bit more tricky, since we have modes like ALTCTL and POSCTL in which the attitude setpoint is generated by a combination of fw position controller and stick mapper function. E.g in ALTCTL pitch_sp and thrust_sp are computed by the controller while roll_sp should be computed by the stick mapper function.

**Comment by mhkabir** [comment]
@tumbili I've been working with obstacle avoidance on multicopters, and have been generating position targets for the avoidance algorithm from a joystick offboard. Eventually, I plan to simply use the stick inputs from RC converted to position targets (much like what is done by mc_pos_ctl in POSCTL currently)

Moving the stick to setpoint functions out of the controllers would thus be something I'm interested in. Would you let me know what needs to be done? :)

**Comment by tumbili** [comment]
@maxb91 We can move the discussion in here.
@mhkabir We are going to come up with some sort of "proposal" on our side,  probably in the form of a PR. Then everybody can comment on it and we can further enhance it.

**Comment by LorenzMeier** [comment]
@mswingtra @yyassa Where is the stick mapper standing?

**Comment by mswingtra** [comment]
@maxb91 could you maybe update here on the current state?

**Comment by LorenzMeier** [comment]
Any news on this?

**Comment by maxb91** [comment]
We ran some first tests of the stick mapper module and they looked good. So far, the manual setpoints for mc_pos_control were implemented and the next step is to also include fw_att_control.

**Comment by tumbili** [comment]
@maxb91 Nice! Could you provide the link to the branch or make a PR? The last link you sent me didn't work so make sure the branch is not private.

**Comment by tumbili** [comment]
@maxb91 Ping me if you need help on this.

**Comment by tumbili** [comment]
The guy who was working on this was fired maybe :-)

**Comment by dagar** [comment]
I can help with this for fixed wing. Where's the current work?

**Comment by LorenzMeier** [comment]
I don't think there is any real work for this. Its probably best to start fresh, in particular given your experience.

**Comment by LorenzMeier** [comment]
@dagar Here is the optimal template to start with:
https://github.com/PX4/Firmware/blob/master/src/modules/land_detector/LandDetector.cpp

The update rate should depend on a param - racing people will want to run the sampling much faster at 100 or 200 Hz.

**Comment by LorenzMeier** [comment]
@dagar Thanks for taking over! @julianoes Don't forget this in your review.

**Comment by dagar** [comment]
I'm not sure if I properly understand the intended design with the work queue. Is the overall goal of this to centralize attitude setpoint in the position controllers, but use the separate thread to publish faster?

**Comment by LorenzMeier** [comment]
No. The goal is to centralise attitude setpoint generation in its own app and the work queue avoids the overhead of creating a complete app on the stack, and instead runs in the work queue stack. Its a very modern design pattern used to be low-latency and resource efficient, also used in responsive frameworks like Node.js.

A position controller should not contain manual flight mode handling. This is the proper way to efficiently not have that in there.

**Comment by dagar** [comment]
**Stick Mapper Design**

Fixed Wing

 - Manual -> publish actuator controls
 - Stabilized -> publish attitude setpoint
 - Altitude -> publish new uorb message with airspeed, altitude, and **turn rate?** setpoints consumed by fw_pos_control.
 - Position -> same as Altitude, but fw_pos_control uses l1 to hold heading 
 - Auto -> publish nothing (eventually allow manual input/adjustment during auto?)

Fixed Wing Notes 
 -  altitude mode could use l1 navigate_heading()
 - pull offsets (eg FW_PSP_OFFSET) into fw_pos_control (otherwise ATSP logging can be confusing)






Multicopter TBD
 - Manual/Stabilized -> publish attitude setpoint
 - Acro -> publish rates setpoint
 - Rattitude -> need to review
 - Altitude ->
 - Position ->
 - Auto ->

**Comment by dagar** [comment]
Coming back to this with a much better understanding of the existing architecture.

Proposed Stick mapper publications:
 MANUAL: publish actuator_controls (I think MC MANUAL should actually just switch to STAB rather than fake it)
 STABILIZED: publish attitude setpoints
 ACRO: publish rate setpoint
 RATTITUDE: switch between rate and attitude setpoints based on control mode. Rattitude threshold would now cause the control flags and subsequent publications to change.
 ALTITUDE: use position setpoint for airspeed, altitude. Need someway to pass roll through, or start treating it like heading.
 POSITION: velocity and altitude for MC, FW roll pass through again

**Questions**
 - How should altitude control roll work? Roll setpoint from sticks passed through via position_setpoints or should the position controller continue to take this directly from manual?
 - Need to review use of manual flaps, gear, aux{1-5} and get them out of the controllers

**Comment by LorenzMeier** [comment]
Closing as stale.
