### ISSUE TITLE
Multicopter altitude hold performance

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2835]
Users are experiencing drops or increase in altitude during movements in the x/y plane.
The goal is to investigate how we can minimize this effect by analyzing the causes.
One cause could be insufficient shielding of the baro from wind.

**Comment by v01d** [comment]
Probable typo on issue title, it says "attitude" instead of "altitude"

**Comment by tumbili** [comment]
Thanks!

**Comment by SimonWilks** [comment]
@tumbili has there been any progress on this front? 

#2790 is relevant to this discussion as well.

**Comment by tumbili** [comment]
@SimonWilks The problem is clearly the barometer. And there is no way of shielding it perfectly such that it's not affected by wind any more. So we need to look at how to teach the estimator not to trust the baro as much in such situations.

**Comment by v01d** [comment]
If you're interested, I've been working on my fork on a variation of INAV
using sonar for altitude hold. I had to also remove the ground detection
since it wasnt reliable. Current INAV trusts too much on baro (which,
besides noise, has considerable drift).

I've worked off stable since I needed that for reliability.

https://github.com/v01d/Firmware/pull/2

In any case, I agree the way forward is with the EKF being tested. I guess
INAV will be phased out right? Otherwise, if there's any interest in my
code, let me know.
