### ISSUE TITLE
Inspect math exception handling path and linkage for CMake NuttX

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#2937]
@davids5 The cmake-2 branch needs this to compile:

```
#if 0
#ifdef __cplusplus
__EXPORT int matherr(struct __exception *e)
{
	return 1;
}
#else
__EXPORT int matherr(struct exception *e)
{
	return 1;
}
#endif
#endif
```

Which raises a few red flags for me.

**Comment by LorenzMeier** [comment]
@davids5 Would be great if you could look into this

**Comment by davids5** [comment]
@LorenzMeier 

I suspected the worst. But after analyzing the differences in compiler options from nuttx_next to cmake:

![image](https://cloud.githubusercontent.com/assets/1945821/11149292/dc935810-89c5-11e5-991b-dc8f3137c690.png)

I think the reason is not so bad, The original make build linked object files against library files. The cmake build for the most part builds libraries and links them (there is only one object file linked and that is  builtin_commands).  This is what is causing the duplicate definition.

As a simple test moving the definition of matherr to the template for builtin_commands.c, the one linked object file, builds just fine.

So Options are:

1) Do nothing - the code from libm returns 0 not 1 as our stub does
```
      If the matherr() function returns zero, then the system sets errno as
       described above, and may print an error message on standard error
       (see below).

       If the matherr() function returns a nonzero value, then the system
       does not set errno, and doesn't print an error message.
```
2) use a -Wl,-wrap matherr - to hide the library version

3) move matherr to linked object module or force the file it is in to linked as an object module.

**Comment by LorenzMeier** [comment]
Its fine as is.
