### ISSUE TITLE
Standard VTOL issues

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#3501]
This is a list of all the issues of the standard VTOL code (many issues will be also applicable to the other VTOL types). The new simulation #3500 will allow to find and fix many of those issues.

 - [ ] Doing a transition in mission: In the simulation the plane starts to pitch up alot during the transition because the pitch setpoint dictates this. I believe the problem is that the multicopter still wants to stay in it's initial position and therefore commands pitch up. This problem was solved in position control mode which works fine in simulation.

 - [x] A mission which consists only of a takeoff and a transition to fw will end up in the plane flying into the ground because it's altitude setpoint will be set to 0 (relative to ground).

**Comment by tumbili** [comment]
@AndreasAntener @SimonWilks @LorenzMeier @sanderux FYI

**Comment by sanderux** [comment]
I seem to have an issue leveling the quad. I had to put the frame several degrees off level to have it level in manual hover. I don't know what this will do to the FW mode. 

i also think trimming should be possible seperately for MC and FW. TRIM_ROLL/PITCH is available for FW but they must now be set manualy because copying trims stores for both MC and FW.

**Comment by tubeme** [comment]
We've had similar experience for a month with the quad pitching up not only in mission but in manual flight transition until 1.1.0. It was in the master branch which we used to fly until 1.1.0. And the pitching of the quad got so intense fighting the plane, that we had a lot of 90 straight up stalls during the transition. We found a way to control it though...Just pulled the throttle down during the transition to make the quad spin on idle speed then when transition finished we pushed the throttle back in order to gain speed for the plane. I don't know if it is related or not... 

After 1.1.0 things got better. Just a couple of days ago we started experiencing back transition problems. The moment we switch to back transition the quad just wants to ditch the VTOL in the ground with almost full pitch down command. We double checked all the CGs and they are correct. Still have to make more flights to confirm consistency of the problem.

**Comment by LorenzMeier** [comment]
This is to track the yaw issue:
https://github.com/PX4/Firmware/issues/3564

**Comment by LorenzMeier** [comment]
This is to track the altitude issue:
https://github.com/PX4/Firmware/issues/3581

**Comment by sanderux** [comment]
@tumbili @AndreasAntener 
I found the pitching up behavior that sitl has also happens in my airframe. In SITL setting FW_PSP_OFF to -25 gives it a somewhat straight transition. I also found strange and dangerous behavior when the takeoff wp and transition wp are inside the acceptance radius.

**Comment by sanderux** [comment]
When reaching the waypoint that comes after a transition command, while the transition has not finished AND the waypoint after that is located on a different heading, the transition fails and the MC continues the mission, sometimes with oscillating pitch behavior.

As this seems inevitable i think the proper action would be to check this in the feasibility checker. Alternatively the mission handler could monitor the transition and fail/RTL if the next WP was reached before transition had completed.

**Comment by AndreasAntener** [comment]
@tumbili Issue one on this list will probably be fixed by your proper TECS handling? https://github.com/PX4/Firmware/pull/3652
