### ISSUE TITLE
The mc_att_control attitude_ sp and thrust_sp output missed serveal times in the fly test.

### ISSUE THREAD

**Issue by CornerOfSkyline** [PX4/Firmware#3635]
I test the standard vtol auto mission. I found that the mc_att_control attitude_ sp and thrust_sp output missed serveal times in the fly test. The motors‘ rotational speed was the armed speed.

The log file is here.

http://logs.uaventure.com/view/psa25rfC5NmgC7EcGqxNM3

**Comment by AndreasAntener** [comment]
Are you talking about the following 0 thrust events during the landing phase?
<img width="1351" alt="screen shot 2016-01-31 at 13 19 16" src="https://cloud.githubusercontent.com/assets/5750020/12702071/9dd1de26-c81d-11e5-81ee-b116474a0cea.png">

**Comment by CornerOfSkyline** [comment]
Yes, it happened during the landing phase.
@AndreasAntener

**Comment by AndreasAntener** [comment]
The problem is that the downwards velocity suddenly gets close to 0 so it thinks it's on the ground and cuts thrust. Pure multicopters have a more constant velocity during landing than VTOLs. In wind they tend to "stop" in air during the landing because the wings generate lift. I'd recommend to try 2 things:
- slightly higher landing speed: MPC_LAND_SPEED to 0.8
- improve Z velocity tuning, for instance try increasing MPC_Z_VEL_P a bit
