### ISSUE TITLE
Landing "kangaroo"

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#3655]
@tumbili Basically thr_max is 0, it's sitting on the ground and practically not moving, landing type setpoint is still active, but then suddenly is allowed to throttle up again. As far as I can tell it's not the free fall detection triggering it.
http://logs.uaventure.com/view/xmkioKbqXpQfcNqBsTpebX
http://logs.uaventure.com/view/c2erHVJtUvqdhfRv7CBUUk

**Comment by sanderux** [comment]
This behavior can be seen in this video at the end: https://drive.google.com/open?id=0B27AvDmVit4KRVlpYkFMNVpTLWM

**Comment by tumbili** [comment]
@AndreasAntener @sanderux The problem could be this one
https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1533
If this condition is not satisfied then the max thrust parameter will not be set to zero any more but rather to standard max thrust value a few lines up in the code. The velocity at / after touchdown is anyway not really accurate any more due to the impact. Will have a closer look tomorrow.

**Comment by tumbili** [comment]
Adressed in #3716
