### ISSUE TITLE
Implement timeout on yaw_reached for waypoints

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#3728]
Implement MIS_YAW_TMT // timeout for accepting waypoint yaw reached in seconds

Disabled: -1 // default
Instant: 0
VTOL: 5 // default

Timeout should not occur when next mission item is a VTOL transition

Lorenz wrote:
@AndreasAntener @sanderux on some waypoints other than takeoff and landing the commanded yaw heading might not be reachable. On some occasions (normal waypoints) we want to weathervane. But on other occasions (aligning before performing a transition) that would be an issue.

After thinking for a bit I would propose to weather-vane for all waypoints expect for a waypoint when followed by a transition. Failure to align should result in a transition abort there.

What do you think?

**Comment by AndreasAntener** [comment]
That sounds like a good approach.

**Comment by sanderux** [comment]
Perhaps we should add an acceptance angle to a waypoint where a transition forward follows

**Comment by sanderux** [comment]
and on all the other waypoints a timeout on _yaw_reached, often the MC forward flight will eventually pull the airframe in the desired yaw so i see no problem with continued attempts to correct yaw.

And maybe as a rule (default configs) the yaw rate should be lower on quadplanes

**Comment by LorenzMeier** [comment]
You're right. We probably should start with just a timeout for VTOL and then accept if position is right.

**Comment by sanderux** [comment]
Any suggested default value for VTOL_WV_WP_TMT (in seconds)?
And I propose that -1 be disabled and 0 considered instant WV.

If we are in agreement i'll get working on this.

**Comment by AndreasAntener** [comment]
I think we're taking about a different timeout. Not to weather vane, but to accept the mission waypoint.

**Comment by sanderux** [comment]
sorry, thats what i meant, i call it weathervane as it would in effect weathervane when traveling to the next waypoint. But that might be confusing to the user.

So, VTOL_WP_YAW_TMT ?

**Comment by sanderux** [comment]
Or maybe add this function globally and disable it by default except on VTOL's?

**Comment by AndreasAntener** [comment]
Maybe a mission parameter MIS_YAW_TMT, default -1 and only the VTOL config will have it set to X.

**Comment by AndreasAntener** [comment]
@sanderux @LorenzMeier Do we agree that we don't care about heading on the waypoints in general for VTOL? So I'd like to change my timeout impl to work as follows, maybe you always thought about it this way (I didn't):

- default, -1, means we wait on yaw (multicopter)
- >= 0 we don't care for yaw on waypoints, except if we have one where we need to force it, then we consider the timeout

How does that sound? My current implementation uses the timeout for all waypoints which makes it hard to set the value right: small enough so it doesn't block the mission too much but long enough so the transition aligning has enough time.

**Comment by sanderux** [comment]
I agree that heading isnt that important, mostly because the heading would align by flying towards the next waypoint (when there is not too much wind).

I would not set a timeout on yaw before transition, that could result in dangerous situations. If we want to support weathervaning on takeoff we need to make this VERY clear.

We now have WV_LTR and WV_LND. I tested LTR and that works fine. I would propose adding WV_NAV and WV_TKF.

We could use the same logic and in case of NAV simply ignore the yaw_reached for normal waypoints. In case of TKF even ignore it on forward transition.

**Comment by AndreasAntener** [comment]
> I would not set a timeout on yaw before transition, that could result in dangerous situations. If we want to support weathervaning on takeoff we need to make this VERY clear.

Maybe I wasn't clear, if the timeout occurs, it would abort the mission at that point.

**Comment by sanderux** [comment]
We could also implement a 2 stage transition if yaw is unreachable. In stage one it engages the pusher to fly towards the next wp only to align yaw with use of the rudder, in stage 2 it attempts transition

**Comment by AndreasAntener** [comment]
Ok I'll finish the timeout as I proposed because it's the simplest way to unblock the current issue.

Any additional yaw handling that you're suggesting is actually independent. Let's say we implement this strategy, then the timeout could be increased but it would still protect it from not reaching the target heading before a transition.

Also, not caring for yaw in general is complementary and necessary to WV on normal waypoints because there it would never reach yaw. So this makes perfect sense if we put everything together after.

**Comment by AndreasAntener** [comment]
Implementation updated and SITL tested.

**Comment by sanderux** [comment]
https://github.com/PX4/Firmware/pull/3740
