### ISSUE TITLE
Low altitude take-off overshoot

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#4819]
When doing auto missions with LPE I noticed this:
## Altitude spike at start of mission

Video:
https://www.youtube.com/watch?v=t7s8027uKZ4

Log:
http://logs.uaventure.com/view/beRXQ3uES9ctPkv2H5ymDQ

I think it is related to the takeoff command, the z setpoint is not showing it, even though the climb does appear in agl, this is in MPC_ALT_MODE = 1 so the controller is tracking AGL.

``` python
pl.figure(figsize=(15,5))
(data.EST0_s7 - data.EST0_s2).plot(label='AGL, m')
(-1*data.LPSP_Z).plot()
data.STAT_MainState.plot()
pl.grid()
pl.legend(loc='best')
```

![image](https://cloud.githubusercontent.com/assets/473772/16050956/b2ade754-322b-11e6-841d-ef55f1fec197.png)

**Comment by dagar** [comment]
Was this ever resolved?

**Comment by MaEtUgR** [comment]
https://github.com/PX4/Firmware/pull/7061 related?

**Comment by Stifael** [comment]
So I have kind of first solution, but need to check for corner cases since the entire auto takeoff is kind of a mess. 
@LorenzMeier: there is however still an issue (also with the current master), that the mc_pos_control and the navigator are not in sync. this means that the mc_pos_controller finishes its takoff, but the navigator remains in the takoff mode. that means that the user has to switch to a new mode to continue

**Comment by LorenzMeier** [comment]
That's not actually the case. If you do a takeoff as an action staying in thst mode is fine and in fact for fixed wing more desirable.

If you do it as Auto mission it will continue with the next item.

We need to focus here on fixing the takeoff ramp / state machine. One thing at a time and iterate fast.

**Comment by Stifael** [comment]
@MaEtUgR will take over

**Comment by MaEtUgR** [comment]
This is potentially related...
I made a predictable smooth takeoff logic without special magic thrust generation in the begining, it's coming in here: https://github.com/PX4/Firmware/pull/7138

While testing the feature I realized that there are situations where it still jumps and that it's most probably not related to my changes. I isolated the problem to be in the auto takeoff logic. When you log with the new logger (ulg) you have the pos_setpoint_tripplets and see the problem:
![auto_takeoff_logic](https://cloud.githubusercontent.com/assets/4668506/25481500/bcf84a58-2b4d-11e7-8919-e977a2e223dc.JPG)
There is a valid triplet loiter point just at the beginning before the takeoff that is usually higher then the actual takeoff point. The behaviour is then pretty unpredictable for me... and I also didn't yet find out why this would happen.

**Comment by LorenzMeier** [comment]
Not critical enough to gate the release.

**Comment by MaEtUgR** [comment]
I think @Stifael found the root cause for the problem I explained earlier (https://github.com/PX4/Firmware/issues/4819#issuecomment-297688753). The glitch always happens when you switch from manual to auto, the navigator and mc_pos_controller are out of sync at the beginning which could lead to this spike. Maybe you can test after we have a fix.

**Comment by Stifael** [comment]
this should now be resolved. It was a general problem when switching from manual to auto. 
If the problem still exists, we can reopen it.
