### ISSUE TITLE
Clean up flash space on FMUv2

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#4957]

**Comment by LorenzMeier** [comment]
134966500 00000256 t crc8_tab
134978900 00000256 t crc_table

**Comment by LorenzMeier** [comment]
135017752 00000256 t mavlink_sha256_constant_256
135020612 00000256 t mavlink_sha256_constant_256
135023928 00000256 t mavlink_sha256_constant_256
135026028 00000256 t mavlink_sha256_constant_256
135027692 00000256 t mavlink_sha256_constant_256
135028148 00000256 t mavlink_sha256_constant_256
135028640 00000256 t mavlink_sha256_constant_256

**Comment by davids5** [comment]
Colaless Mavlink: Due to static inline mavlink/include/mavlink/v2.0/checksum.h

coalesce saves 224

08024ed4 0000001c t crc_accumulate
08038d5e 0000001c t crc_accumulate
0803b530 0000001c t crc_accumulate
0803cb58 0000001c t crc_accumulate
0803d67e 0000001c t crc_accumulate
0804166c 0000001c t crc_accumulate
08044e20 0000001c t crc_accumulate
08045c4c 0000001c t crc_accumulate

coalesce saves 1792
080cbef4 00000100 t mavlink_sha256_constant_256
080cca24 00000100 t mavlink_sha256_constant_256
080cd6f8 00000100 t mavlink_sha256_constant_256
080cdf54 00000100 t mavlink_sha256_constant_256
080ce7c8 00000100 t mavlink_sha256_constant_256
080ce994 00000100 t mavlink_sha256_constant_256
080ceb80 00000100 t mavlink_sha256_constant_256

080c0ba4 00000100 t crc8_tab protocol.h
080c3df4 00000100 t crc_table trone.cpp

coalesce Save 2520:
08038e5c 000001a4 t mavlink_sha256_update
0803b5a8 000001a4 t mavlink_sha256_update
0803cbc4 000001a4 t mavlink_sha256_update
0803dc60 000001a4 t mavlink_sha256_update
08041688 000001a4 t mavlink_sha256_update
08044e80 000001a4 t mavlink_sha256_update
08045c8c 000001a4 t mavlink_sha256_update

Investigate:
0802847c 00000050 t __px4_log_modulename.constprop.0
08077074 00000050 t __px4_log_modulename.constprop.0
08025bc8 00000050 t __px4_log_modulename.constprop.4
08078148 00000050 t __px4_log_modulename.constprop.4
0802d658 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
0805db98 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
080717c4 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
08071f00 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
0807dd08 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
08089290 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
0800421c 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08018c88 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
0801a7f8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08062214 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08063280 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08063888 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08064604 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08072cec 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
0808e23c 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
080940f4 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08041a9c 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.11]
0807ae00 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.11]
0806b9bc 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.12]
0806a1fc 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.13]
08033944 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.14]
080222b0 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
0802dfe8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
080604c4 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
08061af8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
0807a914 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
0807cca4 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
0807fec8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
080bcec8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
080709cc 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.23]
0801bc68 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.3]
08058a4c 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.3]
0800471c 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.4]
0800b98c 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.4]
08035fb4 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.4]
080380a0 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.4]
0804d3f8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.446]
08066ef8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.47]
0807e100 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.5]
08031498 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.6]
080368bc 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.6]
08037274 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.6]
08040264 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.6]
0806d474 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.6]
08032940 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.7]
08036e00 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.7]
0803ba3c 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.7]
08045024 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.7]
0805de04 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.7]
08064ef0 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.7]
0807a160 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.7]
0807a224 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.8]
08056dc8 00000050 t __px4_log_modulename(int, char const*, ...) [clone .constprop.83]
0801e5b4 00000054 t __px4_log_modulename
0802574c 00000054 t __px4_log_modulename
08026430 00000054 t __px4_log_modulename
08027d58 00000054 t __px4_log_modulename
080285f4 00000054 t __px4_log_modulename
08028c30 00000054 t __px4_log_modulename
08028d84 00000054 t __px4_log_modulename
08073b1c 00000054 t __px4_log_modulename
0807b6d0 00000054 t __px4_log_modulename
0800b3e8 00000054 t __px4_log_modulename.constprop.0
08027c00 00000054 t __px4_log_modulename.constprop.0
08079b98 00000054 t __px4_log_modulename.constprop.0
0800ae14 00000054 t __px4_log_modulename.constprop.1
08005064 00000054 t __px4_log_modulename(int, char const*, ...)
08006bbc 00000054 t __px4_log_modulename(int, char const*, ...)
0800c2e0 00000054 t __px4_log_modulename(int, char const*, ...)
0800e61c 00000054 t __px4_log_modulename(int, char const*, ...)
08010c74 00000054 t __px4_log_modulename(int, char const*, ...)
08012654 00000054 t __px4_log_modulename(int, char const*, ...)
0801378c 00000054 t __px4_log_modulename(int, char const*, ...)
080150f8 00000054 t __px4_log_modulename(int, char const*, ...)
08016454 00000054 t __px4_log_modulename(int, char const*, ...)
08017028 00000054 t __px4_log_modulename(int, char const*, ...)
08017b24 00000054 t __px4_log_modulename(int, char const*, ...)
08018f9c 00000054 t __px4_log_modulename(int, char const*, ...)
08019994 00000054 t __px4_log_modulename(int, char const*, ...)
0801cdd4 00000054 t __px4_log_modulename(int, char const*, ...)
0801d9b4 00000054 t __px4_log_modulename(int, char const*, ...)
0801de84 00000054 t __px4_log_modulename(int, char const*, ...)
0801f910 00000054 t __px4_log_modulename(int, char const*, ...)
080224d4 00000054 t __px4_log_modulename(int, char const*, ...)
08022fb8 00000054 t __px4_log_modulename(int, char const*, ...)
08023e70 00000054 t __px4_log_modulename(int, char const*, ...)
08024908 00000054 t __px4_log_modulename(int, char const*, ...)
08024ef0 00000054 t __px4_log_modulename(int, char const*, ...)
08025a28 00000054 t __px4_log_modulename(int, char const*, ...)
080296cc 00000054 t __px4_log_modulename(int, char const*, ...)
0802e47c 00000054 t __px4_log_modulename(int, char const*, ...)
0802f51c 00000054 t __px4_log_modulename(int, char const*, ...)
0802fbbc 00000054 t __px4_log_modulename(int, char const*, ...)
08030b78 00000054 t __px4_log_modulename(int, char const*, ...)
080310b0 00000054 t __px4_log_modulename(int, char const*, ...)
08031ba4 00000054 t __px4_log_modulename(int, char const*, ...)
08032650 00000054 t __px4_log_modulename(int, char const*, ...)
08038d7c 00000054 t __px4_log_modulename(int, char const*, ...)
080469a8 00000054 t __px4_log_modulename(int, char const*, ...)
08055830 00000054 t __px4_log_modulename(int, char const*, ...)
08059870 00000054 t __px4_log_modulename(int, char const*, ...)
0805b988 00000054 t __px4_log_modulename(int, char const*, ...)
080612e4 00000054 t __px4_log_modulename(int, char const*, ...)
0807a00c 00000054 t __px4_log_modulename(int, char const*, ...)
0808c0dc 00000054 t __px4_log_modulename(int, char const*, ...)
0801061c 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
0807c580 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.0]
0802456c 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08024790 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
08093f0c 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.1]
0807e518 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.18]
0801ac90 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.2]
0802394c 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.3]
0800ed6c 00000054 t __px4_log_modulename(int, char const*, ...) [clone .constprop.5]

**Comment by davids5** [comment]
@LorenzMeier 

what commands would we never use:
 [
 dirname
?
basename
break
cat
cd
cmp
cp
date
dd
df
echo
exec
exit
free
help
hexdump
kill
ls
mb
mh
mkdir
mkfatfs
mkfifo
mkrd
mount
mv
mw
ps
pwd
rm
rmdir
set
sh
sleep
test
time
umount
uname
unset
usleep
xd
true
false

Please put an X in front of once I can remove from NuttX and I will disable them in the configs

**Comment by davids5** [comment]
@LorenzMeier 

Reduced command set to 

?
[
break
cat
cd
cmp
cp
date
df
echo
exec
exit
free
help
kill
ls
mkdir
mkfatfs
mount
mv
mw
ps
pwd
rm
rmdir
set
sh
sleep
test
time
umount
unset
usleep
false
true

Saves 4344 Bytes

**Comment by davids5** [comment]
@LorenzMeier  this https://github.com/PX4/Firmware/pull/4994 freesup 4506 Bytes
