### ISSUE TITLE
parameters PWM_AUX_MIN,MAX not implemented

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#5179]
Shouldn't they be referenced here?
https://github.com/PX4/Firmware/blob/master/src/drivers/px4fmu/fmu.cpp#L332

**Comment by julianoes** [comment]
Are they later overwritten by the pwm command?

**Comment by LorenzMeier** [comment]
@kd0aij Use the pwm command to set them during startup. See the main PWM how to do those. Because FMU is not necessary the aux port that seems the more scalable approach. Alternatively we could re-architect the scripts to not use any bash values at all and just rely on params and detect wether the FMU driver runs as AUX or MAIN.

**Comment by kd0aij** [comment]
If I understand correctly, the parameters PWM_AUX_MIN and PWM_AUX_MAX are not used anywhere, and one must instead create a custom airframe which sets bash variables with those same names in the startup script. (rc.interface already looks for those variables)

If that is correct, then it seems those parameters should be deleted.

**Comment by kd0aij** [comment]
@LorenzMeier any comments?

**Comment by kd0aij** [comment]
bump

**Comment by kd0aij** [comment]
closed pending further discussion
