### ISSUE TITLE
SITL unstable on jenkins CI

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#5266]
The sitl test on jenkins has been unreliable since the PR for sitl path fixes. Even after reverting this commit, it still fails on 95% of PR's.

@LorenzMeier @AndreasAntener  @tumbili @julianoes : Any ideas?

![image](https://cloud.githubusercontent.com/assets/473772/17456750/940d083a-5bb0-11e6-87a7-f6a034fcede2.png)

Here is the test log just after the latest commit that passed, that is just a formatting change from the previous commit that passed:

```bash
[ROSUNIT] Outputting test results to /root/.ros/test_results/px4/rostest-launch_mavros_posix_tests_standard_vtol.xml
testmission_test_new_1 ... ok
testmission_test_new_2 ... ok
testmission_test_old_1 ... ok
testmission_test_old_2 ... ok
testmission_test_old_3 ... ok

[ROSTEST]-----------------------------------------------------------------------

[px4.rosunit-mission_test_new_1/test_mission][passed]
[px4.rosunit-mission_test_new_2/test_mission][FAILURE]--------------------------
(vtol_new_2.txt) took too long to get to position lat: 47.399035, lon: 8.543226, alt: 488.143000, xy off: 5.000000, z off: 5.000000, timeout: 600, index: 2, pos_d: 6.268933, alt_d: 11.368000
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/job/Firmware/integrationtests/python_src/px4_it/mavros/mission_test.py", line 275, in test_mission
    self.reach_position(waypoint.x_lat, waypoint.y_long, alt, 600, index)
  File "/job/Firmware/integrationtests/python_src/px4_it/mavros/mission_test.py", line 174, in reach_position
    (self.mission_name, lat, lon, alt, xy_radius, z_radius, timeout, index, self.last_pos_d, self.last_alt_d)))
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[px4.rosunit-mission_test_old_1/test_mission][FAILURE]--------------------------
(vtol_old_1.txt) took too long to get to position lat: 47.399281, lon: 8.547911, alt: 500.144000, xy off: 5.000000, z off: 5.000000, timeout: 600, index: 3, pos_d: 15.013240, alt_d: 0.000000
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/job/Firmware/integrationtests/python_src/px4_it/mavros/mission_test.py", line 275, in test_mission
    self.reach_position(waypoint.x_lat, waypoint.y_long, alt, 600, index)
  File "/job/Firmware/integrationtests/python_src/px4_it/mavros/mission_test.py", line 174, in reach_position
    (self.mission_name, lat, lon, alt, xy_radius, z_radius, timeout, index, self.last_pos_d, self.last_alt_d)))
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[px4.rosunit-mission_test_old_2/test_mission][passed]
[px4.rosunit-mission_test_old_3/test_mission][passed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 5
 * ERRORS: 0
 * FAILURES: 2
```

**Comment by dagar** [comment]
This might be a good excuse to expand the error reporting. How close did it come to finishing successfully? Performance on EC2 can be highly variable.

**Comment by jgoppert** [comment]
The best I can tell it is 15 m off of where it should be.  pos_d: 15.013240, alt_d: 0.000000

@dagar I agree. We need to create jpg on jenkins of each flight.

**Comment by LorenzMeier** [comment]
Here is how build 633 of master looks after it passed:
http://sitl01.dronetest.io/job/PX4%20Firmware%20POSIX%20SITL/633/
http://logs.uaventure.com/view/qZwMF8ZAwhF4UxSLHhJtYm

Here is how build 634 of master looks after it failed:
http://sitl01.dronetest.io/job/PX4%20Firmware%20POSIX%20SITL/634/
http://logs.uaventure.com/view/gHAjvDpj2FrYMGKenr25Ph

Looks like an estimator failure. Most likely due to timing. We have half-lockstep enabled in SITL (the flight code will keep waiting for a delayed / slow sim). We might need full lockstep (the sim waits for delayed flight code).

Given that this is an estimator failure though (which should not happen in half lockstep) it might be something entirely different.

**Comment by LorenzMeier** [comment]
BTW: I don't think Jenkins should generate PNGs - instead it should upload its log file and post the links here as comments.

**Comment by LorenzMeier** [comment]
Well, so it turns out that we had used a tier with CPU credits which means that if our usage went up we were starving on CPUs once we were out of credits.

Which sort of means the more PRs went in, the more failures you would see. I've upgraded the instance now to a compute instance which is twice as expensive but should not toy around.

**Comment by jgoppert** [comment]
@LorenzMeier awesome, thanks!
