### ISSUE TITLE
LPE: Position mode instability

### ISSUE THREAD

**Issue by mayanez** [PX4/Firmware#5411]
Hi,

I was testing LPE today and had some problems with Position hold mode; the copter 'trembles' . The issue goes away when switching to ALT mode. 

Here are the links to the video:
https://drive.google.com/open?id=0B8AjOkamf22UYnRGUGl3cVhrWEU
and the log file:
https://drive.google.com/open?id=0B8AjOkamf22UNl9BM1N1SXhyM2s
(**Note/FYI**: I've renamed attitude rate metric names to ATT_PitchR, ATT_RollR, and ATT_YawR in my log file)

Has anyone seen this behavior?

**Comment by LorenzMeier** [comment]
Hi,

The issue is specific to your airframe and/or the RPI: http://logs.uaventure.com/view/mBXU7JvPygSgaqk47WjiSJ#IMU_Acc_PLOT

Your acceleration range is pretty significant. You have two choices (and you might need to apply both):

  * Check that you have enabled the on-sensor low pass filters for your accelerometer in driver framework. Make sure to have at least 40-80 Hz cutoff, if not lower.
  * Consider damping your autopilot on foam to reduce the incoming vibration

LPE (and EKF2) increase the accuracy of the estimate, but require a properly configured airframe. INAV in contrast never has great performance but works on a flying potato.

**Comment by liaoytal** [comment]
Hi LorenzMeier:
 
   We also met the same problem. Optical Flow Indoor test.
   Position hold mode; the copter 'trembles' . The issue goes away when switching to ALT mode.

   The log file
https://drive.google.com/file/d/0B1tTxziAQDlnWFg4blNNTkV1RVU/view?usp=sharing

 We trying to modify some parameters 
 LPE_ACC_XY, LPE_FLW_XY,MPC_XY_P...
 But it is no use.

**Comment by kapoorshivam100** [comment]
In my case , in the position mode on increasing the throttle above 50 percent it stabilize  for a sec and then starts increasing altitude and throttle on his own...
what could be the posssible error??
