### ISSUE TITLE
Need better test failure reports for CI

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5445]
@AndreasAntener We need to provide better readability of CI test failures. In particular instructions how to reproduce should be printed in the Jenkins console. A good start would be to at least have a minimal output (e.g. VTOL test failed, run `make posix gazebo_standard_vtol`, `commander takeoff` and `commander transition` to verify basic operation).

Note that only a fraction of developers have ROS installed, so we either need alternate instructions like this one or move our testing to something more lightweight like Dronekit.

**Comment by AndreasAntener** [comment]
The MAVROS test will always be ROS. Although one could ask the question if we really need to check via MAVROS and instead just do it with MAVLink. Strictly speaking we want to test the offboard interface, not MAVROS. However, last year I was very happy with that setup because it also spotted breakages coming from the MAVROS side..

The mission tests can potentially be executed normally and we can easily print instructions on how todo that on failure (can QGC still load the non-json mission format?).

**Comment by LorenzMeier** [comment]
Done!
