### ISSUE TITLE
Corner case VTOL_LAND

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#5511]
Presumably: the vtol came out of back transition directly on top of the waypoint. It therefor skipped over the navigation step in the sequence and moved directly to land mode while still having a lot of velocity.

purple: setpoint
red: actual

![selection_002](https://cloud.githubusercontent.com/assets/14801663/18641474/1452985c-7e9d-11e6-8c4e-529b9cb7ba3c.png)

http://logs.uaventure.com/view/yVa84XvfcDNq85UrEcRpuG

**Comment by sanderux** [comment]
Waiting until @AndreasAntener syncs his stuff, after that i can look if / how this could be fixed and if that would still be needed

**Comment by sanderux** [comment]
google earth flight
[flight.kmz.tar.gz](https://github.com/PX4/Firmware/files/480759/flight.kmz.tar.gz)

**Comment by tubeme** [comment]
For the back transition our experience in missions is that the plane always makes the transition too late and always misses its landing point. Then in hover it starts to go back. But you know VTOL and backward movement is not the best combination. It is always better to have the transition way before the landing spot and then go forward in hover until on the spot. We have to take in to account the speed of the plane and its wight in order to calculate properly where the transition should precede the landing spot in mission.

**Comment by sanderux** [comment]
@tubeme Until this is addressed (likely i would calculate distance based on groundspeed) I would recommend using a regular transition command if you want it not to overshoot.
