### ISSUE TITLE
Refuse connection to MissionPlanner as long as it has no PX4 support

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#5768]
Mission planner implements the parameter protocol not according to the MAVLink reference implementation (it was never cross-tested to QGC, which was the reference at the time) which can mess up tuning gains when people try to use it.

We should actively refuse the connection to ensure that PX4 users don't end up with messed up params and a really bad user experience.

The refusal message should be kind though, just hinting that its not supported yet. In an optimal scenario Mission Planner would add support to PX4 and we could add it as GCS option.

**Comment by squilter** [comment]
I think the only proper way to implement this is to have Mission Planner reject the connection. Otherwise, if Mission Planner does add proper support, PX4 would still be rejecting the connection. Even if PX4 is then updated, it still means that older versions of PX4 won't work with Mission Planner because of an artificial restriction.

**Comment by LorenzMeier** [comment]
Good point. I don't want to close the door on that option. I'll talk to Michael to see if he can either add for the param interface (AFAIK the only major problem) or refuse the connection as a stopgap.

**Comment by LorenzMeier** [comment]
Closing this accordingly.
