### ISSUE TITLE
fixedwing_control demo crashes sitl

### ISSUE THREAD

**Issue by squilter** [PX4/Firmware#5811]
I tried to run the fixedwing_control demo, but it would always crash with no error message. I started up sitl with `make posix gazebo_plane`, running Gazebo 7.4.0. When I started ex_fixedwing_demo, Gazebo immediately quit. 

```
pxh> ex_fixedwing_control start
Restoring terminal
[100%] Built target gazebo_plane
```

**Comment by bkueng** [comment]
Looking at the source, this is quite old code, that hasn't been maintained and reworked for SITL Posix. The first step would be to replace the `exit(0)` calls with `return 0`, but there may be more steps necessary to make it work.
It does not crash, it just exits the whole `px4` process instead of only a single thread.

**Comment by dagar** [comment]
@squilter were you able to fix this?

**Comment by squilter** [comment]
No, I was not.

**Comment by dagar** [comment]
Do you still want to? The example is mainly there to show code usage, but is out of date for SITL usage.

**Comment by squilter** [comment]
No thanks, you can keep it closed.
