### ISSUE TITLE
Documentation needed for estimator tuning for high vibration airframes

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#5895]
In the [weekly dev call](http://discuss.px4.io/t/weekly-dev-call-of-november-21-2016/1770) it was suggested that we document how the estimators can be tuned for airframes with high vibrations.

@jgoppert and @priseborough, is this already somewhere in the Devguide? Could you shed some light on this?

This would resolve #5453.

**Comment by priseborough** [comment]
There is currently no tuning guide for the ecl EKF (we do need one, which means I need to write it). The best technique with ecl is to gather a replay log and tune off-line using ekf2_replay. If vibration is causing estimation errors due to aliasing, then gyro and accel process noise parameters can be increased. The innovation levels are the best guide to overall estimator performance.

**Comment by LorenzMeier** [comment]
@priseborough Can you prioritise the documentation for that? It starts to gate the release and I think its really important at this point. It should go into Gitbook. You might need to sign up (log in with Github, don't sign up with one of the other services): https://www.gitbook.com/book/px4/devguide/edit

**Comment by priseborough** [comment]
OK, i will start on it tomorrow.
On 28 Nov. 2016, at 7:10 pm, Lorenz Meier <notifications@github.com<mailto:notifications@github.com>> wrote:


@priseborough<https://github.com/priseborough> Can you prioritise the documentation for that? It starts to gate the release and I think its really important at this point. It should go into Gitbook. You might need to sign up (log in with Github, don't sign up with one of the other services): https://www.gitbook.com/book/px4/devguide/edit
