### ISSUE TITLE
Inspect yaw mixer limiting

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6059]
@Stifael @MaEtUgR I suspect a regression in the yaw mixer limiting. Can you look at that with @priseborough with high prio tomorrow?

**Comment by priseborough** [comment]
@LorenzMeier can you elaborate on the reasons behind your suspicion?

I ran a git blame on mixer_multirotor.cpp.  

https://github.com/PX4/Firmware/blame/c4ccfeae0dcd2a16a676196a9194fbcd8af6e78a/src/modules/systemlib/mixer/mixer_multirotor.cpp

The recent changes to support integration limiting were reporting only, were added inside the rate  limiter and did not change the mixing logic as far as I can tell. The most recent functional change before that were in August/ September 2016 and involved addition and relocation of a slew rate limiter. The last time the core mixing algorithms were touched was in 2015.

**Comment by priseborough** [comment]
I ran a test on the 250-Quad that shows a net thrust increase with large yaw demands and was able to show in the logs that this was not due to mixing, but motor nonlinearity. Here are the yaw demands and sum of esc demands over a period with large yaw disturbances that cause the height to increase with each correction.

![screen shot 2016-12-15 at 7 43 47 pm](https://cloud.githubusercontent.com/assets/3596952/21217148/d04c9c88-c2fe-11e6-89ce-f48b2511c3bb.png)

Here are the esc demands:

![screen shot 2016-12-15 at 7 44 45 pm](https://cloud.githubusercontent.com/assets/3596952/21217172/f36a95e4-c2fe-11e6-830f-29c12ce2cf73.png)

This is hardly surprising - the esc is essentially controlling motor supply voltage proportional to PWM value, static thrust varies with RPM ^2 and therefore the thrust from two motors at 100% PWM is greater than 4 at 50% PWM.

**Comment by LorenzMeier** [comment]
@priseborough I'm referring to the poor tracking on yaw commands here:
http://review.px4.io/plot_app?log=fc450a61-29a5-4dbd-8142-bbedffef577c

This might be combined with an improper setup of the vehicle in terms of mixing, CG or alike.

**Comment by LorenzMeier** [comment]
It was mixing. We still need to make sure the throttle linearisation is set correctly as well.
https://github.com/PX4/Firmware/pull/6086

**Comment by LorenzMeier** [comment]
@tumbili @priseborough I would like to enable the compensation with a conservative and tested default. Right now it is zero: https://github.com/PX4/Firmware/commit/bad2dc80a4458a2f69800cc3029f424fe5e468df

**Comment by LorenzMeier** [comment]
@tumbili @Stifael @MaEtUgR @priseborough Log with the linearisation set to 0.65:
http://review.px4.io/plot_app?log=5387f0af-8576-4419-bed2-f799919331bb
http://review.px4.io/plot_app?log=da33e428-8456-4cde-9aff-1452b8d4388a

Pilots like it better. Note that the GPS quality is crappy in these plots, so don't believe the ground trajectory.

**Comment by kd0aij** [comment]
What improvements were observed with THR_MDL_FAC = 0.65 and is it possible to see them in the logs?
I believe these flights were on a (stock 3S?) 3DR Iris.

**Comment by priseborough** [comment]
I tested master on a 250 quad running a pixracer and did not see any change in esc outputs with adjustment of the THR_MDL_FAC from 0 to 1, when producing full authority yaw demands, so do not think it is working on that board type.

**Comment by kd0aij** [comment]
@priseborough Interesting: how did you make the comparisons between ESC outputs for different parameter values? Using log data or additional debug output?

**Comment by priseborough** [comment]
I was using log data

**Comment by LorenzMeier** [comment]
Ok, so it seems all decent now and we fixed by using the proper mixer.
