### ISSUE TITLE
Missing frsky_telemetry in px4fmu-v2-default.px4

### ISSUE THREAD

**Issue by samo1234** [PX4/Firmware#6294]
since version 1.4.4 there is no frsky_telemetry command or binary.
when the option is enabledin SYS_COMPANION system is stuck.

**Comment by bkueng** [comment]
This module was disabled [0] due to flash restrictions. You can enable it and disable something else, then compile it yourself. If you have a board that support the full 2MB flash (like pixhawk mini), you can also use the px4fmu-v3_default target.

[0] https://github.com/PX4/Firmware/blob/master/cmake/configs/nuttx_px4fmu-v2_default.cmake#L42

**Comment by dagar** [comment]
Hi @samo1234  
frsky_telemetry was temporarily removed from the px4fmu-v2_default build due to flash constraints, but it's back in now.
