### ISSUE TITLE
Fixed wing flight log review

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#6341]
@tumbili @priseborough Would be great if you could have a look at this log where EKF resets. Looking at it I'd say its something funky with the mag, but please come to your own conclusion.

http://review.px4.io/plot_app?log=7c3a1c3f-29b7-42ae-bff5-d4a38cefe271

**Comment by priseborough** [comment]
The EKF delta velocity bias estimates and IMU end of flight accel measurement indicates that this was primarily caused by accel bias errors that were greater than the ekf could handle. The  baro temperature is below 1.5 degC during flight and slowly warming, so a hypothesis is that the vehicle is being operated at a temperature that is significantly lower to the the one used to perform the accel cal and this has caused the large offset.

bias estimates:
![imu accel bias](https://cloud.githubusercontent.com/assets/3596952/23972214/09d43ee4-0a25-11e7-87b7-3cec8a8d35d1.png)

accel data:
![imu end of flight accel meas](https://cloud.githubusercontent.com/assets/3596952/23972221/0e262e9e-0a25-11e7-8ce3-65fee3328d7b.png)
