### ISSUE TITLE
logs.px4 is down?

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/Firmware#6512]
Or is it just my log files that can't be processed?

**Comment by bkueng** [comment]
Since the last update there's a memory leak on the server. I didn't have time to investigate that yet. What happens is that when memory gets low, you cannot reach the server anymore. At some point after, the process will get killed and it will restart, so it will work again. This happens every few days.
I will look into this.

**Comment by bkueng** [comment]
Fixed. It was an issue in the bokeh library.
