### ISSUE TITLE
RTC clock sometimes set to random invalid date

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#662]
- Make GPS -> RTC setting more general, move from ''ubx'' to ''gps''
- Do some filtering when setting date to avoid settig invalid date, don't adjust system clock on each GPS message

**Comment by davids5** [comment]
@DrTon @LorenzMeier 

While I was doing the RTC reset from bootloader work  https://github.com/PX4/Bootloader/issues/16 I had a 3DR GPS+MAG module connected to the PX4. The GPS module did not have lock and it appears that the GPS software kept resetting the system time to be either the last time the GPS saw the light of day, or some hardcoded constant in 2011.

The GPS module should not try to reset the system clock unless it has a valid time.  It seems we need to have a "clock source" and "clock accuracy" mechanism. 

Also Note: HSE to drive the RTC so it is has the potential to have a more accurate time base then an internal OSC, but since we do not have a have an external crystal (32.768Khz) for the LSE and the LSE clock is the only OSC in the backup domain, we cannot keep the RTC running without power on Vdd.  Therefore the time freezes and resumes with power cycles.

**Comment by LorenzMeier** [comment]
There is nothing better than an old rotten issue 8). Here is a potential fix. Please test: #2003

**Comment by davids5** [comment]
@LorenzMeier - was this solved in gps_timefix?

**Comment by LorenzMeier** [comment]
No

**Comment by LorenzMeier** [comment]
This is probably acceptable today.
