### ISSUE TITLE
Mavlink messages getting published slower than requested

### ISSUE THREAD

**Issue by helenol** [PX4/Firmware#6946]
On the stable branch, I'm getting a weird effect on the mavlink output of some high-rate messages such as raw IMU and attitude.
If requesting 20 Hz, get 20 Hz.
If requesting 50 Hz, get 50 Hz.
if requesting 100 Hz, get 83 Hz (was able to get up to 92 Hz by adjusting the loop rate within mavlink_main.cpp)
If requesting 250 Hz, get 160 Hz.
If requesting 500 Hz, get 220 Hz.

And so on... Is anyone else encountering these issues? I've already disabled a bunch of applications to get the CPU load lower and there's definitely enough bandwidth for these messages over the serial link.

Edit: forgot to mention, this is the Pixhawk v2 FMU.

**Comment by LorenzMeier** [comment]
What is the output of the "mavlink status" command?

**Comment by Seanmatthews** [comment]
I was just about to post the same issue...

@helenol @LorenzMeier From what I understand, PX4 is placing an artificial limit of 250Hz on certain (all?) sensors. In my case, I'm using the Snapdragon Flight board, which uses the Invensense MPU9250 IMU. It is 100% capable of higher sample rates, as listed in the data sheet, and demonstrated with Qualcomm's `imu_app`. If you `grep -rn 250HZ` at the repo's top level, you can see these artificial limits. I'm currently working on a quick fix, which I'll post here after I've tested it.

The slowdown to 160Hz and 220Hz that you're seeing is likely from system load.

**Comment by Seanmatthews** [comment]
@helenol Pixhawk v2 FMU spec sheet seems to suggest that it uses the MPU9250 (same as Snapdragon Flight). I changed the magic number [here](https://github.com/PX4/Firmware/blob/master/src/platforms/posix/drivers/df_mpu9250_wrapper/df_mpu9250_wrapper.cpp#L618), from 4 to 2, in order to get 500Hz. Though, in reality I'm getting ~440Hz going through mavlink and mavros.

@LorenzMeier Any idea why it's like this? The comment doesn't provide much background: "The driver empties the FIFO buffer at 1kHz, however we only need to publish at 250Hz."

**Comment by mhkabir** [comment]
@LorenzMeier @helenol I already reported this here : https://github.com/PX4/Firmware/issues/6235

**Comment by mhkabir** [comment]
(Since 2015 : https://github.com/PX4/Firmware/issues/3291)

**Comment by dagar** [comment]
Closing as duplicate.
