### ISSUE TITLE
FTP read file timeouts

### ISSUE THREAD

**Issue by lovettchris** [PX4/Firmware#6984]
I cannot reliably read a file from px4 log directory using mavlink ftp get command.  I get a few packets, then nothing, even with a retry.  Same from QGC.  So I was playing around and found that if I recompile mavlink_ftp.cpp with the conditional flag "MAVLINK_FTP_DEBUG" enabled, then it works perfectly.... so its a weird Heisenberg uncertainty bug... try to watch it and it goes away...

I'm using Pixhawk (px4fmu_v2_default).

**Comment by bkueng** [comment]
This could be a concurrency issue: `MavlinkFTP::handle_message` and `MavlinkFTP::send` are both called from different threads and access class members. The mavlink mission class has the same issue and maybe others too. It needs a proper evaluation and maybe a re-design, because at the moment it is really not clear that they're accessed concurrently.
Making each class thread-safe is probably not solving it either, because both send mavlink messages, which in turn modifies a shared state.

**Comment by LorenzMeier** [comment]
@bkueng Can you look into this? The mission upload fails that result are annoying.

**Comment by dagar** [comment]
FYI - existing mavlink ftp test that's currently broken. https://github.com/PX4/Firmware/tree/master/src/modules/mavlink/mavlink_tests

**Comment by iZhangHui** [comment]
@lovettchris You can try to increase stack size [here](https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_receiver.cpp#L2456) to 
pthread_attr_setstacksize(&receiveloop_attr, PX4_STACK_ADJUSTED(**2400**));

**Comment by LorenzMeier** [comment]
@bkueng Any update on this?

**Comment by bkueng** [comment]
No, I did not look into that yet.

**Comment by LorenzMeier** [comment]
Fixed by @bkueng on master.
