### ISSUE TITLE
LPSP.VZ jump during POSCTL 

### ISSUE THREAD

**Issue by JohnSnowball** [PX4/Firmware#7048]
I made a long flight, all is right except for the altitude hold, the copter seems "floating" in height,(almost no wind), and I checked the log, and found that the LPSP.VZ is not contine from time to time. Here is the "jumping"  moment:
![default](https://cloud.githubusercontent.com/assets/18409502/25029931/3b9f9258-20f4-11e7-8a01-d0184ff61896.png)
I checked that LPOS.Z and LPOS.VZ are both correct and also RC input is continue.
I'm not sure if it's the reason that cause my copter "floating", but I suppose this should be fixed... 
Here is the link of my log  http://logs.uaventure.com/view/pyW2SSFTrx2z72Wvq8z4oU
however, I have to zoom several times to see that jump clearly, so you may not be able to see that online. 

I don't know how to upload a log file here....If you need more log to fix this bug, just tell me how to send the log.
Thx!

**Comment by mzahana** [comment]
I would like to report a similar situation. I have faced this several times using both LPE and EKF3, and using Lidar lightware as range sensor. Recently, I was flying F550 frame with master branch v1.6.0, but without Lidar, only GPS and baro for altitude estimation. I was using EKF2, and was flying fine for couple of lights in Manual/ALTCTL/POSCTL modes. In the last two flights, after 4 successful flights, however, the copter would not go down in ALTCTL mode even though I was pulling the throttle all the way down. I landed in Manual, disarmed, then armed again and tried ALTCTL and POSCTL, and I get the same problem in altitude. Please help in fixing/identifying this issue. A log is available here,
http://logs.uaventure.com/view/HNFY7UpSuabPusXNsj2vzM#_PLOT

**Comment by Stifael** [comment]
@mzahana the second sounds similar to that https://github.com/PX4/Firmware/issues/6604
The first one seems to be mc_pos_,control problem..

**Comment by MaEtUgR** [comment]
The accelerometer z-direction does not clip, just to rule this one out...
![accz_not_clip](https://cloud.githubusercontent.com/assets/4668506/25171500/5718e31a-24ee-11e7-8c77-4115e3e00c3c.JPG)

**Comment by JohnSnowball** [comment]
@MaEtUgR  LPSP.VZ doesn't depend on accel.z, and lpos.z estimated based on accel.z is continue,

**Comment by LorenzMeier** [comment]
@priseborough Can you please chime in and inspect the log?

**Comment by priseborough** [comment]
The second log was using the ecl estimator at commit 7e2597e and exhibits a problem with accelerometer bias estimation that is causing offsets in vertical velocity and position. Unfortunately this problem develops before arming so is not captured in the log. However a vulnerability to timing jitter and high amplitude inputs that could cause incorrect learning of accel bias estimates was fixed in the ecl version we changed to recently, so I would recommend that you update to PX4 master on or after commit ed9a9b7. If the problem persists you can do the following:

1) Use the new logger SYS_LOGGER=1
2) Use a high quality sd card that doesn't produce dropouts in the log (I have good results using a Sandisk extreme 32GB). Increasing the RAM used by the buffer will reduce the dropout length. This is defaulted to 16kB here but can be increased depending on your system configuration 
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS#L857
3) Turn on dedicated replay logging EKF2_REC_RPL=1
4) Turn on logging from boot to disarm SDLOG_MODE=1
5) Post a link to the log in https://github.com/PX4/Firmware/issues/6604

**Comment by MaEtUgR** [comment]
@JohnSnowball We had cases where accel.z problems resulted in wrong vertival velocity estimates hence wrong altitude estimates and the controller tried to compensate using the setpoint LPSP.VZ. But I checked and at least the accelerometer did not clip here in your case.

**Comment by JohnSnowball** [comment]
@MaEtUgR thanks for explain! in fact I'm a bit confused by your discussion, I can't tell which case will solve my bug......

**Comment by MaEtUgR** [comment]
@JohnSnowball I think if you provide a replay log (more detailed for estimation debugging) like described above (https://github.com/PX4/Firmware/issues/7048#issuecomment-296490122) @priseborough will surely have a look at what goes wrong.

@priseborough Does this have any relation to https://github.com/PX4/ecl/pull/265 ?

**Comment by priseborough** [comment]
We are dealing with two separate problem reports here. 

The problem reported by @JohnSnowball looks like a controller set-point issue.

The problem reported by @mzahana is due to estimation error and discussion should be moved to https://github.com/PX4/Firmware/issues/6604.  PX4/ecl#265 is capable of masking the effect of vertical velocity estimation errors but will require the new mode to be selected appropriately on the PX4/Firmware side of the interface.

**Comment by JohnSnowball** [comment]
@MaEtUgR I would like very much to upload a log(I got several with same bug), but I can't paste any here, even I compressed them to ZIP. Do you know any other ways to upload px4log here?

**Comment by tumbili** [comment]
@JohnSnowball use logmuncher, http://logs.uaventure.com/

**Comment by JohnSnowball** [comment]
@tumbili yes, already did that, as I pasted a link at the first http://logs.uaventure.com/view/pyW2SSFTrx2z72Wvq8z4oU 
but for my case, you have to zoom to see the LPSP.VZ discontinuity. I don't know if we can do that with logmucher, I guess a full px4log should be better.

**Comment by TSC21** [comment]
@JohnSnowball what's the current state for you?

**Comment by LorenzMeier** [comment]
Position controller has been revised since, closing as stale.

**Comment by Stifael** [comment]
@JohnSnowball I will close it because we haven't encountered a similar issue. The firmware has changed a lot since then and although I am not able to prove that it is fixed, it is very likely that you will not encounter the same issue again. 
It would be great if you can do another flight test, and if there is anything that seems wrong, then please don't hesitate to reopen this issue or create a new issue.

**Comment by JohnSnowball** [comment]
@TSC21 well, afterwards I use other versions, up to now , I didn't reproduce this bug.

**Comment by JohnSnowball** [comment]
@Stifael Ok, If I met this bug again in the future, I will report that. For the moment, I can't reproduce the same thing.
