### ISSUE TITLE
Unclear firmware version <=> hardware correspondance in documentation

### ISSUE THREAD

**Issue by anuppari** [PX4/Firmware#7324]
It is unclear which firmware version should be used with the [Pixhawk Mini](https://store.3dr.com/products/3dr-pixhawk) (i.e., FMUv2, FMUv3, or FMUv4).
The [documentation page](https://docs.px4.io/en/flight_controller/pixhawk_series.html) lists it as v4, however QGC refuses to flash v4 citing incompatible board ID:
![pic2](https://cloud.githubusercontent.com/assets/3847301/26609374/f6c15da4-455d-11e7-859f-6b248b1937ea.png)

This [release page](https://github.com/PX4/Firmware/releases/tag/v1.5.1) suggests it should be v3, though it lists it as "Pixhawk (2) Mini", even though 3DR nor the documentation pages list it as being a "2", and the pixhawk 2 is a completely different device.

When connecting a new pixhawk mini to QGC, it lists it as having FMUv2. Even after flashing v3 (i.e., "custom" option in QGC), QGC still reads it as having v2 onboard. QGC allows the mini to be flashed by v2 and v3, so it's not clear which one to use:
![pic1](https://cloud.githubusercontent.com/assets/3847301/26609307/bce60710-455d-11e7-8afc-98d8fdd91aba.png)

So which version should be used with the pixhawk mini?

**Comment by anuppari** [comment]
Also, QGC seems to automatically download v2, so is that the correct one?

![pic3](https://cloud.githubusercontent.com/assets/3847301/26609816/c21ebf6c-4560-11e7-9a5e-4bde68c7861a.png)

**Comment by mhkabir** [comment]
v2 or v3 for the Pixhawk Mini. The v3 target uses the full 2MB flash. 

I will fix the documentation in a minute. Sorry about the confusion.

**Comment by anuppari** [comment]
What is the full flash used for? I've seen some mention of needing a different firmware for using the LPE instead of the EKF, does v3 include both?

**Comment by mhkabir** [comment]
Yes v3 includes both

**Comment by dagar** [comment]
I believe this has been improved. Please reopen if I'm wrong.

**Comment by charles-blouin** [comment]
Hi,

I would like to confirm that the V3 seems like the right firmware. The V2 outputs an error (GRYO 0 not found). V4 refuses to install. The documentation [here](https://docs.px4.io/en/flight_controller/pixhawk_series.html#fmu-versions) on the wiki seems wrong.

**Comment by dagar** [comment]
@charles-blouin which board do you have and which version of the Firmware did you try?

**Comment by charles-blouin** [comment]
This is with a Pixhawk mini. I used the px4fmu-v3_default.px4 firmware on the [github](https://github.com/PX4/Firmware/releases) release page, which Qgroundcontrol reports as 1.7.0. I was able to perform the calibrations and correctly display the attitude in Qgroundcontrol.

I am new to the PX4 environment. When I received the Pixhawk Mini, I flashed the new firmware using the default firmware in Qground control, and I kept obtaining the error Preflight fail: no gyro sensor 0. I spend a few hours researching this. The information of the wiki I linked above confused me. If I connect the Pixhawk Mini in Qgroundcontrol, the board reports as a PX4 FMU V2 in the firmware tab. Then, when I flash the firmware using the default PX4 flight stack, the gyro is not recognized and the calibration fails. I tried to manually flash the firmware for the FMU v4 using the Custom Firmware file option, but that report a board id error and the firmware does not upload. In the end, only the firmware for the v3 FMU worked.

**Comment by LorenzMeier** [comment]
@santiago3dr Could you re-test with QGC and Pixhawk Mini?

**Comment by charles-blouin** [comment]
Additionnal information:
Here is a screenshot of what happens when I plugin the Pixhawk mini:
![image](https://user-images.githubusercontent.com/7013617/34277264-fa0d1e38-e672-11e7-89f2-43558c3cd771.png)
When I was flashing the firmware using the default configuration as in the image above, Qgroundcontrol was downloading the v2 firmware version, and it had the Preflight fail: no gyro sensor 0.
Now that I have flashed the v3 version, when I reflash the board, it defaults to the V3 firmware, which works.

**Comment by santiago3dr** [comment]
There was an issue with the pixhawk mini running 1.7.1 that flagged the error of No gyro and No accel found.
Said error was fixed in 1.7.2 as per commit b718901

Successfully flashed stable/default firmware on pixhawk mini with qgroundcontrol:
![1](https://user-images.githubusercontent.com/13203106/34277528-08875ebe-e65b-11e7-9ced-e5d70e8b3c1a.JPG)
![2](https://user-images.githubusercontent.com/13203106/34277536-0e0f21b4-e65b-11e7-8cba-88a7851a314e.JPG)

**Comment by charles-blouin** [comment]
I would like to update the [gitbook](https://docs.px4.io/en/flight_controller/pixhawk_series.html#fmu-versions) documentation. Can I confirm that the correct firmware is the px4fmu-v3_default.px4? Is there a reason Qgroundcontrol specifies FMU v2 and the gitbook says it is FMU v4?

**Comment by dagar** [comment]
@charles-blouin px4fmu-v2 and px4fmu-v3 are nearly the same, except the v3 has access to the full 2MB of flash. PX4 includes more modules (like UAVCAN) only in the v3. If you look in the firmware you'll see that px4fmu-v3_default is actually px4fmu-v2_large.

Due to the bootloader that the pixhawk mini ships with we can't automatically flash fmu-v3 through QGC, but you can still do it manually. 

I've opened https://github.com/PX4/px4_user_guide/pull/121 to fix the documentation. Sorry about the confusion.

**Comment by LorenzMeier** [comment]
The Gitbook docs seem correct, because it correctly states that FMUv4 is Pixracer.

**Comment by hamishwillee** [comment]
@LorenzMeier FYI, that text just got updated following this issue.

**Comment by KJBB** [comment]
After floundering for months, I see a post from someone who is likely to be able to help. I have posted on various forums without success.

I have two Pixracer flight controllers, and neither has any SERIAL_ or FRSKY_ parameters present in the parameter list. I've just reflashed the "latest" via QGC - http//px4-travis.s3.amazonaws.com/firmware/stable/px4fmu-v4_default.px4.
No luck. A search for SER or FRSKY in the parameter list draws a blank.

I tried to use GitHub and forked and cloned multi-megabytes. I tried to find the makefile I wanted, but ended up guessing which was the correct one. I ran it anyway and it started and then said something was missing! Damn.
I feel I have been running several marathons in sequence, just to get firmware that I had expected to be there in the first place. I am exhausted, confused, and contemplating buying a new Pixracer just to see what I get!
I think I "updated" the firmware on each drone on first use, and possibly threw away the parameters I want? I'm extremely pi.... off, and lost as to my next step.
I noted the comment "Is there a reason Qgroundcontrol specifies FMU v2" which makes me wonder if QGC is limiting my choice somehow, despite the px4fmu-v4_default.px4 result that appears to be the best a man can get?

Do you think you can rescue a lost soul?
Ken Barrie - Scotland.
