### ISSUE TITLE
Unable to get lock with LPE v1.6.1

### ISSUE THREAD

**Issue by akshaykalkunte** [PX4/Firmware#7347]
We are unable to get the green lock with Pixhawk and PX4 v.1.6.1. The estimator is set to LPE, with the parameters configured respectively. Lidar Lite RangeFinder was used to determine the altitude, disabling the Maxbotix sensor values. The optical flow, flow gyro compensation, pub agl as lpos down were selected for LPE_FUSION parameter. Flow Quality set to 75. 
We intend to use it for completely indoor navigation and hence require the flow values for accurate position estimation. What could be the issue?

**Comment by LorenzMeier** [comment]
You need to flash `px4fmu-v3_default` if you run on Pixhawk and want to use LPE. We don't have enough flash to support it on the default build. Note that you need an STM32 processor with the right silicon revision in order to be able to use this additional flash.

I have made this more obvious in this commit: c9a28fc0eb
