### ISSUE TITLE
Fixed Wing reject auto mission

### ISSUE THREAD

**Issue by jinchengde** [PX4/Firmware#8361]
fixed wing cannot entry into auto mission

here is the flight log
https://logs.px4.io/plot_app?log=90d6dcd2-7b87-4963-9390-987c1d062b4a
https://logs.px4.io/plot_app?log=27b7223c-7d7b-4dba-b82a-da3229e546e0

**Comment by dagar** [comment]
Auto mission is being rejected because you don't have a valid position estimate.

![image](https://user-images.githubusercontent.com/84712/33243186-49f7af44-d2af-11e7-83a3-a0778b1152b7.png)

![image](https://user-images.githubusercontent.com/84712/33243246-5f2c7060-d2b0-11e7-9cce-165ff043c57b.png)

[6fb19372-e027-4b23-b0e8-5425d409f5f3.ulg.pdf](https://github.com/PX4/Firmware/files/1504138/6fb19372-e027-4b23-b0e8-5425d409f5f3.ulg.pdf)

@priseborough could you take a look at these logs?

**Comment by priseborough** [comment]
The inertial navigation is failing due to high vibration You need to reduce vibration levels by correct isolation of the autopilot.

Very high vibration levels
![screen shot 2017-11-27 at 8 17 08 am](https://user-images.githubusercontent.com/3596952/33244447-6352bfe6-d34b-11e7-86f0-8eeee2fba001.png)

GPS vertical velocity and baro vertical position innovations are diverging in the same direction
![screen shot 2017-11-27 at 8 17 58 am](https://user-images.githubusercontent.com/3596952/33244453-80f6c54c-d34b-11e7-8b22-8cfe8accf000.png)

**Comment by jinchengde** [comment]
thanks @priseborough
