### ISSUE TITLE
Yaw control not behaving as expected with stable release v1.7.0

### ISSUE THREAD

**Issue by vmishra9** [PX4/Firmware#8484]
I tuned a quadcopter with X configuration. The step and impulse response of roll, pitch and yaw angles was up to the mark during the manual flight. I gave a mission to the quadcopter. The flight was smooth until a location where a yaw of more than 90 degrees. The yaw of the vehicle went in the opposite direction of the setpoint for the yaw. This made the quadcopter oscillate dangerously for some amount of time.

I repeated the same mission and observed the same behavior. I am attaching the yaw response of the quadcopter for the two flights. Can anyone tell me what could be issue?

![yaw1](https://user-images.githubusercontent.com/23639165/34091077-5f610702-e3e1-11e7-962d-dd0a8efceb2b.png)
![yaw2](https://user-images.githubusercontent.com/23639165/34091078-5f9e608e-e3e1-11e7-8585-3ab99b306773.png)

**Comment by LorenzMeier** [comment]
Yaw wraps at +-180 degrees and the system chooses the shortest rotation direction, so it didn't go into the opposite direction but the shortest.

The oscillations are due to improperly tuned yaw gains (YAW_P or YAWSPEED_P). They are too high for your system and show critical oscillation. You will want to reduce the YAW_P gain to 50-70% of its current value and re-try.
