### ISSUE TITLE
Go to DESCEND mode while GPS always connected

### ISSUE THREAD

**Issue by JohnSnowball** [PX4/Firmware#8515]
**Bug Report** 

I got a crash during a vtol flight, the flight mode changed to "NAVIGATION_STATE_DESCEND" at the end of front transition. Then it's goes lower and lower, when I found it is wrong, I tried to save it by turn on RTL, but it's too late.

I checked source code, it seems the only way to go into that mode is GPS timeout, but I checked my GPS, at least the altitude data looks good.
here's my log link:
https://logs.px4.io/plot_app?log=d5bbeb04-40dc-464b-bcd8-408cad3983f5

**Comment by dagar** [comment]
This was an estimator problem.

![image](https://user-images.githubusercontent.com/84712/34282338-8db505dc-e692-11e7-93e7-abe68ce62dcb.png)

![image](https://user-images.githubusercontent.com/84712/34282354-babc56c0-e692-11e7-811c-827229a8b75c.png)

![image](https://user-images.githubusercontent.com/84712/34282363-c4c254e4-e692-11e7-9808-6050282789b1.png)

According to estimator_status.filter_fault_flags it was bad accelerometer data.

**Comment by JohnSnowball** [comment]
@dagar So first is accelerometer fault -> ekf estimator got a wrong vel/pos estimation -> afterwards although GPS works well, ekf2 rejects GPS fusion as there's a big difference -> ekf2 thinks GPS timeout.

Am I correct?

**Comment by JohnSnowball** [comment]
![image](https://user-images.githubusercontent.com/18409502/34283561-6677a482-e707-11e7-8b5a-1ef1221208cb.png)
And I saw this abnormal sampling regularity, what does it mean? Does it mean my accelerometer has something wrong?

**Comment by dagar** [comment]
I think those are just missed samples in the log, but I'd have to look at what flight review is doing. If you have a higher quality sdcard it usually helps. I would guess your problems are vibration, but it's hard to see in the log due to filtering. That's something we're hoping to improve in the near future.

Does that line up with what you see first hand? See if you can tighten things, balance props, etc, and if it's still an issue we can adjust the EKF.

**Comment by dagar** [comment]
You can see it corresponding with the pusher.

![image](https://user-images.githubusercontent.com/84712/34302362-782504b2-e6fe-11e7-811f-1e1afa1b0ded.png)

**Comment by dagar** [comment]
Once more with the solution status flags as well (scaled to fit).

![image](https://user-images.githubusercontent.com/84712/34302571-847cf2b4-e6ff-11e7-9ce0-75407944d1cf.png)

**Comment by dagar** [comment]
Closing as this isn't really a Firmware issue, but I still hope we can significantly improve the detection and handling of these issues (with updated IMU drivers and different filtering) for the next PX4 release.

**Comment by Antiheavy** [comment]
> If you have a higher quality sdcard it usually helps.

We have started using the fastest available U3 rated SDcards we can find in all our PX4 based autopilots.  "Normal" SDcards are too slow and always have many small gaps in the data logs.



> I would guess your problems are vibration, but it's hard to see in the log due to filtering. That's something we're hoping to improve in the near future.

+1 for improved filtering (turning off internal IMU filters) so that vibration can properly be measured/detected!

> So first is accelerometer fault -> ekf estimator got a wrong vel/pos estimation -> afterwards although GPS works well, ekf2 rejects GPS fusion as there's a big difference -> ekf2 thinks GPS timeout.

This happens to us sometimes too.  I hope there will be some improvements coming to ekf2 to make it more robust eventually...

**Comment by JohnSnowball** [comment]
@dagar  I checked other log files, I couldn't found bad raw acceleration data like this during transition.
I agree that it's not firmware bug, it could be some mechanical problem. Next time I will do more pre-checks.
@Antiheavy I prefer to make more checks on my side, we can't throw everything to EKF2. I wish both of us have less chance of crash. XD
