### ISSUE TITLE
Flightmode not updated after Boot

### ISSUE THREAD

**Issue by tops4u** [PX4/Firmware#8613]
**Bug Report** 

After a Reboot the Flightmode is not correctly transfered to QGC. It will show Manual. Current Stable 1.7.2. I belive Custom Mode reflects Flight Mode Selection? 

Just after Reboot (while RC FM-Switch being in Position Stabilized):

![fm_manual_after_boot](https://user-images.githubusercontent.com/6877067/34644687-96e5115a-f33b-11e7-9338-6d731a746ca5.png)

After switching from Stab -> PosCtl -> Stab:

![fm_after_posctl-stab](https://user-images.githubusercontent.com/6877067/34644690-a228aa40-f33b-11e7-9933-71aa0fb149ab.png)

**Comment by dagar** [comment]
Do you have a corresponding log to verify? You could also take a look on the command line. `commander status`

**Comment by tops4u** [comment]
TLog? Or what log file would you require?

**Comment by tops4u** [comment]
Duplicate to #8268

**Comment by tops4u** [comment]
Checked with listener commander_state and listener vehicle_status just after Boot Main State is 0 Nav State 0. After toggling the FM Switch on the TX Main State goes to 8, Nav State to 15.

**Comment by dagar** [comment]
Reading the original description here again I'm now guessing the original switch to position was ignored (likely no valid position available).

I'm wondering if there's something we could do to better handle this case. Perhaps the RC state at bootup should be respected as long as a mode change hasn't been commanded (RC or Mavlink), or any attempted vehicle arming. Either the disarmed system could initialize the main_state based on bootup RC position, or we evaluate RC switch positions under certain conditions (rather than only on changes).

We have to be careful with automating changing modes to not do something even less intuitive.

**Comment by tops4u** [comment]
Checked on Vehicle after Arming (Spinning Rotors) the Flightmode is not updated. How is this supposed to work? Respectively I would assume that then I Power RC and Vehicle that the FlightController would take whatever Flightmode is selected on the RC System.

**Comment by tops4u** [comment]
AFAIK this is still the case, also with current Master.
