### ISSUE TITLE
Velocity setpoint jump in auto mode

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#8863]
@Stifael @MaEtUgR FYI
I found that the copter was a bit too aggressive during an auto mission although the max acceleration was relatively low (2 m/s/s).
Looking at the log I found that the velocity setpoint was not smooth (see the jumps).
Is there a setting I need to change or is this bug?

![image](https://user-images.githubusercontent.com/7610489/36037655-b41ee0ba-0dbd-11e8-8819-1ac398400007.png)

In manual mode I found it quite smooth as was the velocity setpoint in the log.

**Comment by Stifael** [comment]
@RomanBapst there is no smoothing auto anymore. There is a velocity feedforward along track and position setpoint perpendicular to track, although the feedforward term is incorporated into the position setpoint due to legacy reason. 
The logic is quite simple now. The vehicle always just follow the previous-current line, where it accelerates with MPC_ACC_HOR. The speed at the current waypoint is defined by the angle previous-current-next. 
Can you send the entire log? Did you change MPC_ACC_HOR_MAX or MPC_ACC_HOR?

**Comment by RomanBapst** [comment]
Fixed in #10746
