### ISSUE TITLE
Quadplane tailsitter

### ISSUE THREAD

**Issue by LorenzMeier** [PX4/Firmware#8961]
Fix this: http://discuss.px4.io/t/vtol-quadplane-tailsitter-cannot-finish-transition-phase/5110

**Comment by RomanBapst** [comment]
Comments:

- airspeed mode parameter was set to use groundspeed as airspeed, validate that this works
- check if the transition bug in manual mode #8990 is not responsible for this
- elevon actuation is present in transition but very little. Is this because we feed the control signal from the motors to the elevons as well?

**Comment by dagar** [comment]
That flight predates the vtol poll changes. https://github.com/PX4/Firmware/blob/3098c77c9168553c5085636fc4b0428e78568bc3/src/modules/vtol_att_control/vtol_att_control_main.cpp#L692
