### ISSUE TITLE
【mc_att_control】 Remove unnecessary defaults.

### ISSUE THREAD

**Issue by xdwgood** [PX4/Firmware#9077]
:smiley:  I don't think we need this extra variable.　https://github.com/PX4/Firmware/blob/master/src/modules/mc_att_control/mc_att_control_main.cpp#L95　
This variable `ATTITUDE_TC_DEFAULT`　is used to adjust the pid.　
Use it here:　https://github.com/PX4/Firmware/blob/master/src/modules/mc_att_control/mc_att_control_main.cpp#L534
I think we can use this parameter `MC_ROLL_TC`　to **directly** adjust the pid.　https://github.com/PX4/Firmware/blob/master/src/modules/mc_att_control/mc_att_control_params.c#L54
It is also a mistake to follow the current logic.　https://github.com/PX4/Firmware/blob/master/src/modules/mc_att_control/mc_att_control_params.c#L45
Should : **Increase** if the system is too twitchy, **Reduce** if the response is too slow and sluggish.

@MaEtUgR  @Stifael  Do I understand that correctly?　:rabbit2:

**Comment by MaEtUgR** [comment]
@xdwgood Don't use the `TC` parameters, I just recently requested to take them out: https://github.com/PX4/Firmware/pull/8003/commits/a349bd8cea7246eb6fb5f3ae7a2b00c7c49c657b
It will likely get merged soon.

`TC` stands for time constant. It just the inverse of a gain -> `K = 1/TC`
In this implementation it was multiplied to the gain as `GAIN * 0.2/TC` which means if you stay on default parameters (which is 0.2) it multiplies by 1 and has no effect.
If you changed the parameter you blindly rescale the gains of rate and attitude control loop... which makes no sense from a control perspective and only generates confusion in my opinion. That's why I deleted them.
