### ISSUE TITLE
 A litttle upload problem. 

### ISSUE THREAD

**Issue by KJNKJNKJN** [PX4/Firmware#9288]
![image](https://user-images.githubusercontent.com/22700138/38614236-f574e358-3dbe-11e8-8a5b-7d8c736eb459.png)

When upload the program,  shell will ends with the above picture. Although it succeed,but i really want to know how to end with this output:
Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.

[100%] Built target upload

Thank you!

**Comment by mcsauder** [comment]
Hi @KJNKJNKJN , Does this stand out as an issue to you from your screen capture above?  I would seem to think that this could be part of your problem.  Perhaps not?

![image](https://user-images.githubusercontent.com/2497951/40265015-37ceea64-5aed-11e8-9dd1-87f433f26e5d.png)

**Comment by mcsauder** [comment]
Hi @KJNKJNKJN , Can you post your repo branch, version, etc. ?

**Comment by julianoes** [comment]
What exactly is the issue. I'm trying to understand.

**Comment by KJNKJNKJN** [comment]
@julianoes  @mcsauder  the PX4 Firmware version is 1.7. When download the programme, it does not end with output:
Erase : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.

[100%] Built target upload

.Althougth the upload succeed. thank you.

**Comment by mcsauder** [comment]
Hi @KJNKJNKJN ,
 
Please try this, delete your clone of the PX4/Firmware repository, re-clone it, complete a 
```
git submodule update --init --recursive
```

then, depending on your particular hardware configuration, complete something that matches your hardware version such as:

```
make px4fmu-v4_default upload
```

and if your hardware is v2, substitute v2 instead of v4, etc., ...

Next, report back to us.  We are very interested in helping you, please feel free to DM us on slack to get through this, we have all been in your position previously.  Good luck!

-Mark

**Comment by KJNKJNKJN** [comment]
@mcsauder thank you very much.  I try it.

**Comment by mcsauder** [comment]
@KJNKJNKJN , 

Any luck?  If you have had success shall we move to close the issue?

-Mark
