### ISSUE TITLE
submodule lib/ecl unable to checkout

### ISSUE THREAD

**Issue by potaito** [PX4/Firmware#9338]
I am unable to checkout the most recent commit of `lib/ecl` https://github.com/PX4/ecl/commit/8678cc42ba6c87b3ae0724af2becb62b71bf6683.

When freshly cloning the px4 firmware and then updating the submodules, I also get the error:

```
$ git clone git@github.com:PX4/Firmware.git
$ cd Firmware
$ git submodule init
$ git submodule update --recursive
```

I then end up with this:

```
$ git status

On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
(commit or discard the untracked or modified content in submodules)

        modified: src/lib/ecl (new commits, modified content)

no changes added to commit (use "git add" and/or "git commit -a")
```

Not sure where the problem is or how this slipped through CI :neutral_face:

**Comment by potaito** [comment]
Will push fix in a moment

**Comment by dagar** [comment]
This sometimes happens when a Firmware change with corresponding submodule change goes in. For the sake of testing and review the Firmware is pointed at another branch in the submodule that it requires. They're both merged (and branches deleted), and now the exact submodule commit is missing.

Example: https://github.com/PX4/Firmware/pull/9319

We need to make sure the submodule commits in Firmware master/beta/stable always point at submodule commit that's going to exist indefinitely.

**Comment by potaito** [comment]
Got it. I think I fixed it by checking out the corresponding commit that exists on libecl's master: 
https://github.com/PX4/Firmware/pull/9339
