### ISSUE TITLE
PixHack v5 issues

### ISSUE THREAD

**Issue by thomasgubler** [PX4/Firmware#9600]

**Comment by bkueng** [comment]
Issues on Pixhack v5 on master that I noticed when bench-testing:
 - **SD card does not work at all**. Mounting consistently fails (I tested on 2 boards). This is the bootup output:
  ```
		nsh: mount: mount failed: No such device
		nsh: mkfatfs: mkfatfs failed: File table overflow
```
- **internal mag detected as external**.
  pixhawk 4 boot output:
  ```
		INFO  [ist8310] no device on bus 1
		INFO  [ist8310] no device on bus 2
		IST8310 on I2C bus 3 at 0x0e (bus: 100 KHz, max: 400 KHz)
  ```
   Pixhack v5 output:
  ```
		INFO  [ist8310] no device on bus 1
		IST8310 on I2C bus 2 at 0x0e (bus: 100 KHz, max: 400 KHz)
		INFO  [ist8310] no device on bus 5
  ```
  The internal bus is 3, but on the Pixhack the ist8310 is on bus 2.
- **3DR telemetry does not work due to incompatible pinout**
	  - Pinout: http://doc.cuav.net/flight-controller/pixhack-v5/en/
- **Included wifi**: works but frequent connection losses (I cannot calibrate sensors using it)

**Comment by vooon** [comment]
I also had error with microsd, but i fixed it by formatting card (with regular format from gnome nautilus).
Wifi working fine.
Mag also on bus 2, but external (gps module) on bus 1.

```
HW arch: PX4FMU_V5
HW type: V511
HW version: 0x00000001
HW revision: 0x00000001
FW git-hash: 58dd7be12a40579293faa03e3ac7ac8e3cc6b679
FW version: 1.8.0 80 (17301632)
OS: NuttX
OS version: Release 7.22.0 (118882559)
OS git-hash: 0ac630e6d0e90480121c74d59a92676f0b951dce
Build datetime: May  9 2018 09:37:46
Build uri: BUILD_URI
Toolchain: GNU GCC, 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
MFGUID: 36353937313751010033002a
MCU: STM32F76xxx, rev. Z
UID: 33002A:31375101:36353937 
```

**Comment by bkueng** [comment]
Thanks for the tip @vooon, reformatting worked for me as well.

**Comment by jinger26** [comment]
@bkueng @thomasgubler  we can close this issue. This was developer-edition bench testing. Since then manufacture has released new version of hardware.
