### ISSUE TITLE
jMAVSim HITL Navigation Failure

### ISSUE THREAD

**Issue by mrehan3** [PX4/Firmware#9718]
**Describe the bug**
I am trying to run a HITL simulation using jMAVSim following these instructions: https://dev.px4.io/en/simulation/hitl.html. I am running the master PX4 firmware. Whenever I try to takeoff, the shell says "Takeoff detected" and then it says "CRTICIAL NAVIGATION FAILURE - CHECK SENSOR CALIBR". Then it goes completely unstable and moves uncontrollably with the Pixhawk flashing purple light.

**Expected behavior**
I expected the drone to takeoff and hold in position.

**Log File**
Log file: https://logs.px4.io/plot_app?log=db2a6cfd-84ef-4971-87d3-dc897e542431

These are the messages I see:
MSG: ARMED by arm/disarm component command
MSG: [logger] file: /fs/microsd/log/2018-06-19/17_31_4
MSG: Takeoff detected
MSG: MANUAL CONTROL LOST (at t=139348ms)
MSG: MANUAL CONTROL REGAINED after 666ms
MSG: CRITICAL NAVIGATION FAILURE - CHECK SENSOR CALIBR
MSG: Failsafe enabled: no local position
MSG: Failsafe mode enabled

**Drone:**

* Describe the type of drone: 
DJI Flame Wheel F450Quadrotor x (4011)

**Additional context**
SITL simulation is working fine for me, but only having this trouble with HITL.

**Comment by mrehan3** [comment]
Sometimes the navigation doesn't fail, but it says "Takeoff detected" and "Landing detected" as I move the throttle stick, but nothing happens in the GUI.

According to this flight log: https://logs.px4.io/plot_app?log=86679494-993a-410d-aca1-b1f8eb9cf326 

It seems as though it is getting the throttle RC input, but it is not changing the z velocity or local z position.

**Comment by LorenzMeier** [comment]
Can you please configure the HITL multicopter configuration instead? That will likely resolve your issue.

**Comment by mrehan3** [comment]
I just tried that, and it has the same issue (getting a throttle input but no change in the z position and no movement in the jMAVSim) 

Log: https://logs.px4.io/plot_app?log=832a6e3f-f057-4172-ab60-79ca36708934

**Comment by mrehan3** [comment]
I just tried AirSim (https://dev.px4.io/en/simulation/airsim.html), and it has the same issue (says takeoff/landing detected, but nothing happens in the simulator). This means that it definitely isn't a problem with the simulator, but something wrong with the firmware I would suspect. Any ideas? Could someone try HITL and see if it's working for them?

**Comment by LorenzMeier** [comment]
@bkueng Could Nico try this and report back?

**Comment by mrehan3** [comment]
Just for some more info, HITL works on my Pixhawk using v1.4.4 firmware (I just picked some old version to see if maybe there was something wrong with my hardware), but it doesn't work with v1.8. I will try to find the newest version where HITL works.

**Comment by mrehan3** [comment]
Yes, HITL also work on v1.7.0 stable release.

**Comment by bkueng** [comment]
> @bkueng Could Nico try this and report back?

@nicovanduijn ^

**Comment by nicovanduijn** [comment]
I've been trying to reproduce, but couldn't so far. When setting COM_RC_IN_MODE to Joystick/No RC Checks it arms and takes off just fine on my machine. I'm looking for an RC now to see if I can reproduce

**Comment by nicovanduijn** [comment]
@mrehan3 It works just fine for me with a PixRacer and a Taranis.

- What hardware are you using? (Flight controller, RC)
- Can you once again confirm that you are 
   a) Running PX4 v1.8 (seems fine from the log you uploaded though)
   b) Have chosen the HIL Quadcopter X in Airframe (reboot to apply setting)
   c) Have unchecked all AutoConnect boxes except for UDP under the General tab of the settings menu 
        in QGC
   d) Have set NAV_DLL_ACT to "Disabled"
   e) Have set COM_RC_IN_MODE to "RC Transmitter" if you are indeed using a remote as described
   f) Have your remote properly bound to the receiver and calibrated with QGC

If all of those are as we expect, my guess is as good as yours... It works on my machine

**Comment by mrehan3** [comment]
@nicovanduijn 

It still doesn't work for me on v1.8 :(

- The hardware I am using is the 3DR Pixhawk 1 and the FS-TH9X RC.

a) Reloaded PX4 v1.8 again (log and QGroundControl confirm that it's running v1.8)
b) Definitely chose HIL Quadcopter X (confirmed in log and QGroundControl)
c) Unchecked everything except UDP
d) NAV_DLL_ACT is disabled
e) COM_RC_IN_MODE is set to "RC Transmitter"
f) RC is correctly bound and callibrated (can see throttle and other stuff moving in QGroundControl)

Here are some more logs:
On v1.7 (it works here): https://logs.px4.io/plot_app?log=7960fcec-40d0-429b-8f80-cc48eed67642
On v1.8 (does not work here, just says takeoff/landing detected): https://logs.px4.io/plot_app?log=b53ec207-f810-4c1f-aba7-97b39bb7448a

**Comment by sivateja619** [comment]
@nicovanduijn 
I am using pixhawk 1 by Radiolink and followed all the steps you mentioned. I am still facing the same issue. 

Another question :
When i uploaded the V1.7 .px4 using QGC, i am still using the latest repository of firmware that i have cloned to use jMAVSim HITL command. 
Is that okay ??


Thanks

**Comment by mrehan3** [comment]
@sivateja619 I used the latest repository to run the jMAVSim command and it worked fine for me when v1.7 was flashed onto the pixhawk (through QGC)

**Comment by nicovanduijn** [comment]
@sivateja619 I'm not sure how backwards compatibility is. To be on the safe side, just do a 
`git checkout tags/v1.7.0 && git submodule update --init --recursive`.

@mrehan3 I found a pixhawk 1 laying around somewhere and was indeed able to reproduce what you described. Haven't had time to get to the bottom of it yet. Seems that HITL and v1.8 on the pixhawk 1 doesn't work

**Comment by sivateja619** [comment]
@nicovanduijn I was able to downgrade to V1.7 but, while testing HITL, can see the quad flipping by itself and shooting up an error "check sensor calibr". Also, i tried with  COM_RC_IN_MODE to Joystick/No RC Checks.
Arming/disarming, selecting flight modes is all good. But, the flight itself is an issue. 

SITL is working fine.

Is it a problem with my hardware (pixhawk 1 by Radiolink) ?

**Comment by v01d** [comment]
Hi, I'm having a similar issue: trying HIL on pixhawk FMUv2 and I get zero output on hil actuator controls even though everything else seems OK. I traced this (I think) to pwm_out_sim not being present on the firmware, which I guess is responsible for outputting the actuator controls. See the error about the command not found. It seems that this command is not built for FMUv2, is this intentional?

<pre>
nsh> INFO  [logger] Start file log
INFO  [logger] Opened log file: /fs/microsd/log/2018-07-10/21_52_44.ulg
INFO  [commander] Takeoff detected
INFO  [commander] Landing detected
WARN  [load_mon] init low on stack! (268 bytes left)
WARN  [load_mon] init low on stack! (268 bytes left)
WARN  [load_mon] init low on stack! (268 bytes left)
WARN  [load_mon] init low on stack! (268 bytes left)
INFO  [logger] closed logfile, bytes written: 213472
WARN  [platforms__common] Reboot NOW.
WARN  [dri�
FMUv2 ver 0x8 : Rev 0 V2
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
HW arch: PX4FMU_V2
HW type: V2
HW version: 0x00090008
HW revision: 0x00000000
FW git-hash: 96443b3cf3e3adaec8b2ebb6c83a19a92d40a13f
FW version: Release 1.8.0 (17301759)
OS: NuttX
OS version: Release 7.22.0 (118882559)
OS git-hash: 63775322bf25adb406594f8e610122fe0cef2f7a
Build datetime: Jun 19 2018 06:36:49
Build uri: BUILD_URI
Toolchain: GNU GCC, 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
MFGUID: 373839333034511100380033
MCU: STM32F42x, rev. 1

WARNING   WARNING   WARNING!
Revision 1 has a silicon errata:
This device can only utilize a maximum of 1MB flash safely!
https://pixhawk.org/help/errata

UID: 380033:30345111:37383933 
[hardfault_log] Fault Log is Armed
INFO  [tune_control] Publishing standard tune 1
INFO  [param] selected parameter default file /fs/mtd_params
rgbled on I2C bus 2 at 0x55 (bus: 100 KHz, max: 100 KHz)
nsh: rgbled_pwm: command not found
INFO  [dataman] In flight restart, data manager file '/fs/microsd/dataman' size is 350216 bytes
INFO  [load_mon] stack check enabled
ERROR [param] Parameter UAVCAN_ENABLE not found
nsh: pwm_out_sim: command not found
INFO  [tune_control] Start playback...
WARN  [load_mon] init low on stack! (268 bytes left)
INFO  [tune_control] Playback finished.
ERROR [px4io] RECOVERING FROM FMU IN-AIR RESTART
WARN  [commander] Failsafe enabled: no RC
WARN  [load_mon] init low on stack! (268 bytes left)
px4io re-sending arm cmd
INFO  [px4io] default PWM output device
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS1 @ 57600B
INFO  [mavlink] mode: Onboard, data rate: 80000 B/s on /dev/ttyS2 @ 921600B
ERROR [param] Parameter UAVCAN_ENABLE not found
px4flow [159:100]
WARN  [px4flow] scanning I2C buses for device..
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
ERROR [mavlink] offboard mission init failed (-1)
INFO  [init] Mixer: /etc/mixers/quad_x.main.mix on /dev/pwm_output0 
INFO  [init] Mixer: /etc/mixers/pass.aux.mix appended to /dev/pwm_output0 
INFO  [logger] logger started (mode=all)
</pre>

**Comment by v01d** [comment]
Confirmed my suspcicion, see discussion here: https://github.com/PX4/Firmware/commit/22acb1dab1483fcbf618a8836864750ff8596b8f#r28613651

Could be re-enable this by default? Or is flash size limiting? Maybe there's another not so critical module that can be disabled instead, loosing HITL ability is pretty bad IMHO.

**Comment by nicovanduijn** [comment]
I believe @bkueng made this change to limit the flash space usage. You may not be able to fit the firmware into memory on the older hardware, but give it a shot

**Comment by v01d** [comment]
I finally recompiled with the module enabled and indeed this was the reason for zero outputs. Anyways, the outputs were really erratic. They would appear to react to actuator targets but oscilate between minimum and maximum very aggressively. For now I will not continue with HIL as it seems there are still some problems.
