### ISSUE TITLE
Failsafe PWM not set

### ISSUE THREAD

**Issue by knopancakes** [PX4/Firmware#9775]
The following line  rc.interface is erroneous:

https://github.com/PX4/Firmware/blob/0ac1ef12c77ef5a0db05d22bab4cfbd61b0c24a6/ROMFS/px4fmu_common/init.d/rc.interface#L119

The PWM driver expects a -p before the failsafe value. Additionally, the failsafe command expects a -m or -c argument, which is not provided here.

**Comment by mcsauder** [comment]
Thanks @knopancakes ,

Can you let me know if the following gives you the expected behavior at that line? 
`pwm failsafe -c 12345678 -p ${FAILSAFE} -d ${OUTPUT_DEV}`
or, 
`pwm failsafe -c ${PWM_OUT} -p ${FAILSAFE} -d ${OUTPUT_DEV}`

If either line does I can add it to my current startup script work.

Thanks.

-Mark

**Comment by knopancakes** [comment]
I can confirm that providing the -p flag is the correct fix.

`pwm failsafe -c ${PWM_OUT} -p ${FAILSAFE} -d ${OUTPUT_DEV}`

**Comment by knopancakes** [comment]
Unfortunately I do not have hardware with me at the moment so I cannot verify the script, but I am pretty sure
